package j2735.DSRC;

import asn2pojo.runtime.annotations.Asn1Property;
import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class AccelerationSet4Way extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "long")
	@JsonProperty("long")
	private Acceleration long_;
	@Asn1Property(tag = 1)
	private Acceleration lat;
	@Asn1Property(tag = 2)
	private VerticalAcceleration vert;
	@Asn1Property(tag = 3)
	private YawRate yaw;

	public Acceleration getLong_() {
		return long_;
	}

	public void setLong_(Acceleration long_) {
		this.long_ = long_;
	}

	public Acceleration getLat() {
		return lat;
	}

	public void setLat(Acceleration lat) {
		this.lat = lat;
	}

	public VerticalAcceleration getVert() {
		return vert;
	}

	public void setVert(VerticalAcceleration vert) {
		this.vert = vert;
	}

	public YawRate getYaw() {
		return yaw;
	}

	public void setYaw(YawRate yaw) {
		this.yaw = yaw;
	}

	AccelerationSet4Way() {
		super(false);
	}
}