package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import asn2pojo.runtime.serialization.IntegerDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class Acceleration extends Asn1Integer {

	public Acceleration() {
		super(-2000L, 2001L);
	}

	@JsonCreator
	public Acceleration(long value) {
		this();
		this.value = value;
	}

	public static class AccelerationDeserializer extends IntegerDeserializer<Acceleration> {
		public AccelerationDeserializer() {
			super(Acceleration.class);
		}

		@Override
		protected Acceleration construct() {
			return new Acceleration();
		}
	}
}