package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonSerialize(using = AccelerationConfidenceSerializer.class)
@JsonDeserialize(using = AccelerationConfidenceDeserializer.class)
public enum AccelerationConfidence implements Asn1Enumerated {
	unavailable(0, "unavailable"), accl_100_00(1, "accl-100-00"), accl_010_00(2, "accl-010-00"), accl_005_00(3,
			"accl-005-00"), accl_001_00(4, "accl-001-00"), accl_000_10(5,
					"accl-000-10"), accl_000_05(6, "accl-000-05"), accl_000_01(7, "accl-000-01");

	private final int index;
	private final String name;

	public int getIndex() {
		return index;
	}

	public String getName() {
		return name;
	}

	public boolean hasExtensionMarker() {
		return false;
	}

	private AccelerationConfidence(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public int maxIndex() {
		return 7;
	}
}