package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.annotation.JsonProperty;
import j2735.REGION.Reg_AdvisorySpeed;
import asn2pojo.runtime.types.Asn1SequenceOf;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class AdvisorySpeed extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private AdvisorySpeedType type;
	@Asn1Property(tag = 1, optional = true)
	@JsonDeserialize(using = SpeedAdvice.SpeedAdviceDeserializer.class)
	private SpeedAdvice speed;
	@Asn1Property(tag = 2, optional = true)
	private SpeedConfidence confidence;
	@Asn1Property(tag = 3, optional = true)
	@JsonDeserialize(using = ZoneLength.ZoneLengthDeserializer.class)
	private ZoneLength distance;
	@Asn1Property(tag = 4, name = "class", optional = true)
	@JsonProperty("class")
	@JsonDeserialize(using = RestrictionClassID.RestrictionClassIDDeserializer.class)
	private RestrictionClassID class_;
	@Asn1Property(tag = 5, optional = true)
	private SequenceOfRegional regional;

	public AdvisorySpeedType getType() {
		return type;
	}

	public void setType(AdvisorySpeedType type) {
		this.type = type;
	}

	public SpeedAdvice getSpeed() {
		return speed;
	}

	public void setSpeed(SpeedAdvice speed) {
		this.speed = speed;
	}

	public SpeedConfidence getConfidence() {
		return confidence;
	}

	public void setConfidence(SpeedConfidence confidence) {
		this.confidence = confidence;
	}

	public ZoneLength getDistance() {
		return distance;
	}

	public void setDistance(ZoneLength distance) {
		this.distance = distance;
	}

	public RestrictionClassID getClass_() {
		return class_;
	}

	public void setClass_(RestrictionClassID class_) {
		this.class_ = class_;
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_AdvisorySpeed> {
		SequenceOfRegional() {
			super(j2735.REGION.Reg_AdvisorySpeed.class, 1L, 4L);
		}
	}

	public SequenceOfRegional getRegional() {
		return regional;
	}

	public void setRegional(SequenceOfRegional regional) {
		this.regional = regional;
	}

	AdvisorySpeed() {
		super(true);
	}
}