package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class AntennaOffsetSet extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private Offset_B12 antOffsetX;
	@Asn1Property(tag = 1)
	private Offset_B09 antOffsetY;
	@Asn1Property(tag = 2)
	private Offset_B10 antOffsetZ;

	public Offset_B12 getAntOffsetX() {
		return antOffsetX;
	}

	public void setAntOffsetX(Offset_B12 antOffsetX) {
		this.antOffsetX = antOffsetX;
	}

	public Offset_B09 getAntOffsetY() {
		return antOffsetY;
	}

	public void setAntOffsetY(Offset_B09 antOffsetY) {
		this.antOffsetY = antOffsetY;
	}

	public Offset_B10 getAntOffsetZ() {
		return antOffsetZ;
	}

	public void setAntOffsetZ(Offset_B10 antOffsetZ) {
		this.antOffsetZ = antOffsetZ;
	}

	AntennaOffsetSet() {
		super(false);
	}
}