package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class AxleWeightSet extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	@JsonDeserialize(using = AxleLocation.AxleLocationDeserializer.class)
	private AxleLocation location;
	@Asn1Property(tag = 1, optional = true)
	@JsonDeserialize(using = AxleWeight.AxleWeightDeserializer.class)
	private AxleWeight weight;

	public AxleLocation getLocation() {
		return location;
	}

	public void setLocation(AxleLocation location) {
		this.location = location;
	}

	public AxleWeight getWeight() {
		return weight;
	}

	public void setWeight(AxleWeight weight) {
		this.weight = weight;
	}

	AxleWeightSet() {
		super(true);
	}
}