package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonSerialize(using = BasicVehicleRoleSerializer.class)
@JsonDeserialize(using = BasicVehicleRoleDeserializer.class)
public enum BasicVehicleRole implements Asn1Enumerated {
	basicVehicle(0, "basicVehicle"), publicTransport(1, "publicTransport"), specialTransport(2,
			"specialTransport"), dangerousGoods(3, "dangerousGoods"), roadWork(4, "roadWork"), roadRescue(5,
					"roadRescue"), emergency(6, "emergency"), safetyCar(7, "safetyCar"), none_unknown(8,
							"none-unknown"), truck(9, "truck"), motorcycle(10, "motorcycle"), roadSideSource(11,
									"roadSideSource"), police(12, "police"), fire(13, "fire"), ambulance(14,
											"ambulance"), dot(15, "dot"), transit(16, "transit"), slowMoving(17,
													"slowMoving"), stopNgo(18, "stopNgo"), cyclist(19,
															"cyclist"), pedestrian(20, "pedestrian"), nonMotorized(21,
																	"nonMotorized"), military(22, "military");

	private final int index;
	private final String name;

	public int getIndex() {
		return index;
	}

	public String getName() {
		return name;
	}

	public boolean hasExtensionMarker() {
		return false;
	}

	private BasicVehicleRole(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public int maxIndex() {
		return 22;
	}
}