package j2735.DSRC;

import asn2pojo.runtime.annotations.Asn1Property;
import asn2pojo.runtime.types.Asn1Sequence;
import asn2pojo.runtime.types.Asn1SequenceOf;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import j2735.REGION.Reg_BasicSafetyMessage;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class BasicSafetyMessage extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private BSMcoreData coreData;
	@Asn1Property(tag = 1, optional = true)
	private SequenceOfPartII partII;
	@Asn1Property(tag = 2, optional = true)
	private SequenceOfRegional regional;

	public BSMcoreData getCoreData() {
		return coreData;
	}

	public void setCoreData(BSMcoreData coreData) {
		this.coreData = coreData;
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfPartII extends Asn1SequenceOf<BSMpartIIExtension> {
		SequenceOfPartII() {
			super(BSMpartIIExtension.class, 1L, 8L);
		}
	}

	public SequenceOfPartII getPartII() {
		return partII;
	}

	public void setPartII(SequenceOfPartII partII) {
		this.partII = partII;
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_BasicSafetyMessage> {
		SequenceOfRegional() {
			super(Reg_BasicSafetyMessage.class, 1L, 4L);
		}
	}

	public SequenceOfRegional getRegional() {
		return regional;
	}

	public void setRegional(SequenceOfRegional regional) {
		this.regional = regional;
	}

	BasicSafetyMessage() {
		super(true);
	}
}