package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Bitstring;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonDeserialize(using = BrakeAppliedStatusDeserializer.class)
public class BrakeAppliedStatus extends Asn1Bitstring {

	public boolean isUnavailable() {
		return get(0);
	}

	public void setUnavailable(boolean unavailable) {
		set(0, unavailable);
	}

	public boolean isLeftFront() {
		return get(1);
	}

	public void setLeftFront(boolean leftFront) {
		set(1, leftFront);
	}

	public boolean isLeftRear() {
		return get(2);
	}

	public void setLeftRear(boolean leftRear) {
		set(2, leftRear);
	}

	public boolean isRightFront() {
		return get(3);
	}

	public void setRightFront(boolean rightFront) {
		set(3, rightFront);
	}

	public boolean isRightRear() {
		return get(4);
	}

	public void setRightRear(boolean rightRear) {
		set(4, rightRear);
	}

	public BrakeAppliedStatus() {
		super(5, false, new String[]{"unavailable", "leftFront", "leftRear", "rightFront", "rightRear"});
	}
}