package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 *******************************************************************************
 *
 * This source file was generated by a tool. Beware manual edits might be
 * overwritten in future releases. asn1jvm v1.0-SNAPSHOT
 *
 *******************************************************************************
 * Copyright 2024 USDOT
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class BSMcoreData extends Asn1Sequence {

	@Asn1Property(tag = 0)
	@JsonDeserialize(using = MsgCount.MsgCountDeserializer.class)
	private MsgCount msgCnt;
	@Asn1Property(tag = 1)
	private TemporaryID id;
	@Asn1Property(tag = 2)
	@JsonDeserialize(using = DSecond.DSecondDeserializer.class)
	private DSecond secMark;
	@Asn1Property(tag = 3)
	@JsonDeserialize(using = Latitude.LatitudeDeserializer.class)
	private Latitude lat;
	@Asn1Property(tag = 4, name = "long")
	@JsonProperty("long")
	@JsonDeserialize(using = Longitude.LongitudeDeserializer.class)
	private Longitude long_;
	@Asn1Property(tag = 5)
	@JsonDeserialize(using = Elevation.ElevationDeserializer.class)
	private Elevation elev;
	@Asn1Property(tag = 6)
	private PositionalAccuracy accuracy;
	@Asn1Property(tag = 7)
	private TransmissionState transmission;
	@Asn1Property(tag = 8)
	@JsonDeserialize(using = Speed.SpeedDeserializer.class)
	private Speed speed;
	@Asn1Property(tag = 9)
	@JsonDeserialize(using = Heading.HeadingDeserializer.class)
	private Heading heading;
	@Asn1Property(tag = 10)
	@JsonDeserialize(using = SteeringWheelAngle.SteeringWheelAngleDeserializer.class)
	private SteeringWheelAngle angle;
	@Asn1Property(tag = 11)
	private AccelerationSet4Way accelSet;
	@Asn1Property(tag = 12)
	private BrakeSystemStatus brakes;
	@Asn1Property(tag = 13)
	private VehicleSize size;

	BSMcoreData() {
		super(false);
	}
}