package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class BSMcoreData extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private MsgCount msgCnt;
	@Asn1Property(tag = 1)
	private TemporaryID id;
	@Asn1Property(tag = 2)
	private DSecond secMark;
	@Asn1Property(tag = 3)
	private Latitude lat;
	@Asn1Property(tag = 4, name = "long")
	@JsonProperty("long")
	private Longitude long_;
	@Asn1Property(tag = 5)
	private Elevation elev;
	@Asn1Property(tag = 6)
	private PositionalAccuracy accuracy;
	@Asn1Property(tag = 7)
	private TransmissionState transmission;
	@Asn1Property(tag = 8)
	private Speed speed;
	@Asn1Property(tag = 9)
	private Heading heading;
	@Asn1Property(tag = 10)
	private SteeringWheelAngle angle;
	@Asn1Property(tag = 11)
	private AccelerationSet4Way accelSet;
	@Asn1Property(tag = 12)
	private BrakeSystemStatus brakes;
	@Asn1Property(tag = 13)
	private VehicleSize size;

	public MsgCount getMsgCnt() {
		return msgCnt;
	}

	public void setMsgCnt(MsgCount msgCnt) {
		this.msgCnt = msgCnt;
	}

	public TemporaryID getId() {
		return id;
	}

	public void setId(TemporaryID id) {
		this.id = id;
	}

	public DSecond getSecMark() {
		return secMark;
	}

	public void setSecMark(DSecond secMark) {
		this.secMark = secMark;
	}

	public Latitude getLat() {
		return lat;
	}

	public void setLat(Latitude lat) {
		this.lat = lat;
	}

	public Longitude getLong_() {
		return long_;
	}

	public void setLong_(Longitude long_) {
		this.long_ = long_;
	}

	public Elevation getElev() {
		return elev;
	}

	public void setElev(Elevation elev) {
		this.elev = elev;
	}

	public PositionalAccuracy getAccuracy() {
		return accuracy;
	}

	public void setAccuracy(PositionalAccuracy accuracy) {
		this.accuracy = accuracy;
	}

	public TransmissionState getTransmission() {
		return transmission;
	}

	public void setTransmission(TransmissionState transmission) {
		this.transmission = transmission;
	}

	public Speed getSpeed() {
		return speed;
	}

	public void setSpeed(Speed speed) {
		this.speed = speed;
	}

	public Heading getHeading() {
		return heading;
	}

	public void setHeading(Heading heading) {
		this.heading = heading;
	}

	public SteeringWheelAngle getAngle() {
		return angle;
	}

	public void setAngle(SteeringWheelAngle angle) {
		this.angle = angle;
	}

	public AccelerationSet4Way getAccelSet() {
		return accelSet;
	}

	public void setAccelSet(AccelerationSet4Way accelSet) {
		this.accelSet = accelSet;
	}

	public BrakeSystemStatus getBrakes() {
		return brakes;
	}

	public void setBrakes(BrakeSystemStatus brakes) {
		this.brakes = brakes;
	}

	public VehicleSize getSize() {
		return size;
	}

	public void setSize(VehicleSize size) {
		this.size = size;
	}

	BSMcoreData() {
		super(false);
	}
}