package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class ConfidenceSet extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	private AccelSteerYawRateConfidence accelConfidence;
	@Asn1Property(tag = 1, optional = true)
	private SpeedandHeadingandThrottleConfidence speedConfidence;
	@Asn1Property(tag = 2, optional = true)
	private TimeConfidence timeConfidence;
	@Asn1Property(tag = 3, optional = true)
	private PositionConfidenceSet posConfidence;
	@Asn1Property(tag = 4, optional = true)
	private SteeringWheelAngleConfidence steerConfidence;
	@Asn1Property(tag = 5, optional = true)
	private HeadingConfidence headingConfidence;
	@Asn1Property(tag = 6, optional = true)
	private ThrottleConfidence throttleConfidence;

	public AccelSteerYawRateConfidence getAccelConfidence() {
		return accelConfidence;
	}

	public void setAccelConfidence(AccelSteerYawRateConfidence accelConfidence) {
		this.accelConfidence = accelConfidence;
	}

	public SpeedandHeadingandThrottleConfidence getSpeedConfidence() {
		return speedConfidence;
	}

	public void setSpeedConfidence(SpeedandHeadingandThrottleConfidence speedConfidence) {
		this.speedConfidence = speedConfidence;
	}

	public TimeConfidence getTimeConfidence() {
		return timeConfidence;
	}

	public void setTimeConfidence(TimeConfidence timeConfidence) {
		this.timeConfidence = timeConfidence;
	}

	public PositionConfidenceSet getPosConfidence() {
		return posConfidence;
	}

	public void setPosConfidence(PositionConfidenceSet posConfidence) {
		this.posConfidence = posConfidence;
	}

	public SteeringWheelAngleConfidence getSteerConfidence() {
		return steerConfidence;
	}

	public void setSteerConfidence(SteeringWheelAngleConfidence steerConfidence) {
		this.steerConfidence = steerConfidence;
	}

	public HeadingConfidence getHeadingConfidence() {
		return headingConfidence;
	}

	public void setHeadingConfidence(HeadingConfidence headingConfidence) {
		this.headingConfidence = headingConfidence;
	}

	public ThrottleConfidence getThrottleConfidence() {
		return throttleConfidence;
	}

	public void setThrottleConfidence(ThrottleConfidence throttleConfidence) {
		this.throttleConfidence = throttleConfidence;
	}

	ConfidenceSet() {
		super(true);
	}
}