package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import j2735.REGION.Reg_ConnectionManeuverAssist;
import asn2pojo.runtime.types.Asn1SequenceOf;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class ConnectionManeuverAssist extends Asn1Sequence {

	@Asn1Property(tag = 0)
	@JsonDeserialize(using = LaneConnectionID.LaneConnectionIDDeserializer.class)
	private LaneConnectionID connectionID;
	@Asn1Property(tag = 1, optional = true)
	@JsonDeserialize(using = ZoneLength.ZoneLengthDeserializer.class)
	private ZoneLength queueLength;
	@Asn1Property(tag = 2, optional = true)
	@JsonDeserialize(using = ZoneLength.ZoneLengthDeserializer.class)
	private ZoneLength availableStorageLength;
	@Asn1Property(tag = 3, optional = true)
	private WaitOnStopline waitOnStop;
	@Asn1Property(tag = 4, optional = true)
	private PedestrianBicycleDetect pedBicycleDetect;
	@Asn1Property(tag = 5, optional = true)
	private SequenceOfRegional regional;

	public LaneConnectionID getConnectionID() {
		return connectionID;
	}

	public void setConnectionID(LaneConnectionID connectionID) {
		this.connectionID = connectionID;
	}

	public ZoneLength getQueueLength() {
		return queueLength;
	}

	public void setQueueLength(ZoneLength queueLength) {
		this.queueLength = queueLength;
	}

	public ZoneLength getAvailableStorageLength() {
		return availableStorageLength;
	}

	public void setAvailableStorageLength(ZoneLength availableStorageLength) {
		this.availableStorageLength = availableStorageLength;
	}

	public WaitOnStopline getWaitOnStop() {
		return waitOnStop;
	}

	public void setWaitOnStop(WaitOnStopline waitOnStop) {
		this.waitOnStop = waitOnStop;
	}

	public PedestrianBicycleDetect getPedBicycleDetect() {
		return pedBicycleDetect;
	}

	public void setPedBicycleDetect(PedestrianBicycleDetect pedBicycleDetect) {
		this.pedBicycleDetect = pedBicycleDetect;
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_ConnectionManeuverAssist> {
		SequenceOfRegional() {
			super(j2735.REGION.Reg_ConnectionManeuverAssist.class, 1L, 4L);
		}
	}

	public SequenceOfRegional getRegional() {
		return regional;
	}

	public void setRegional(SequenceOfRegional regional) {
		this.regional = regional;
	}

	ConnectionManeuverAssist() {
		super(true);
	}
}