package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.types.IA5String;
import asn2pojo.runtime.annotations.Asn1Property;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class DataParameters extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	private IA5String processMethod;
	@Asn1Property(tag = 1, optional = true)
	private IA5String processAgency;
	@Asn1Property(tag = 2, optional = true)
	private IA5String lastCheckedDate;
	@Asn1Property(tag = 3, optional = true)
	private IA5String geoidUsed;

	public IA5String getProcessMethod() {
		return processMethod;
	}

	public void setProcessMethod(IA5String processMethod) {
		this.processMethod = processMethod;
	}

	public IA5String getProcessAgency() {
		return processAgency;
	}

	public void setProcessAgency(IA5String processAgency) {
		this.processAgency = processAgency;
	}

	public IA5String getLastCheckedDate() {
		return lastCheckedDate;
	}

	public void setLastCheckedDate(IA5String lastCheckedDate) {
		this.lastCheckedDate = lastCheckedDate;
	}

	public IA5String getGeoidUsed() {
		return geoidUsed;
	}

	public void setGeoidUsed(IA5String geoidUsed) {
		this.geoidUsed = geoidUsed;
	}

	DataParameters() {
		super(true);
	}
}