package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class DDateTime extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	@JsonDeserialize(using = DYear.DYearDeserializer.class)
	private DYear year;
	@Asn1Property(tag = 1, optional = true)
	@JsonDeserialize(using = DMonth.DMonthDeserializer.class)
	private DMonth month;
	@Asn1Property(tag = 2, optional = true)
	@JsonDeserialize(using = DDay.DDayDeserializer.class)
	private DDay day;
	@Asn1Property(tag = 3, optional = true)
	@JsonDeserialize(using = DHour.DHourDeserializer.class)
	private DHour hour;
	@Asn1Property(tag = 4, optional = true)
	@JsonDeserialize(using = DMinute.DMinuteDeserializer.class)
	private DMinute minute;
	@Asn1Property(tag = 5, optional = true)
	@JsonDeserialize(using = DSecond.DSecondDeserializer.class)
	private DSecond second;
	@Asn1Property(tag = 6, optional = true)
	@JsonDeserialize(using = DOffset.DOffsetDeserializer.class)
	private DOffset offset;

	public DYear getYear() {
		return year;
	}

	public void setYear(DYear year) {
		this.year = year;
	}

	public DMonth getMonth() {
		return month;
	}

	public void setMonth(DMonth month) {
		this.month = month;
	}

	public DDay getDay() {
		return day;
	}

	public void setDay(DDay day) {
		this.day = day;
	}

	public DHour getHour() {
		return hour;
	}

	public void setHour(DHour hour) {
		this.hour = hour;
	}

	public DMinute getMinute() {
		return minute;
	}

	public void setMinute(DMinute minute) {
		this.minute = minute;
	}

	public DSecond getSecond() {
		return second;
	}

	public void setSecond(DSecond second) {
		this.second = second;
	}

	public DOffset getOffset() {
		return offset;
	}

	public void setOffset(DOffset offset) {
		this.offset = offset;
	}

	DDateTime() {
		super(false);
	}
}