package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import asn2pojo.runtime.serialization.IntegerDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class DMonth extends Asn1Integer {

	public DMonth() {
		super(0L, 12L);
	}

	@JsonCreator
	public DMonth(long value) {
		this();
		this.value = value;
	}

	public static class DMonthDeserializer extends IntegerDeserializer<DMonth> {
		public DMonthDeserializer() {
			super(DMonth.class);
		}

		@Override
		protected DMonth construct() {
			return new DMonth();
		}
	}
}