package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import asn2pojo.runtime.serialization.IntegerDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class DSecond extends Asn1Integer {

	public DSecond() {
		super(0L, 65535L);
	}

	@JsonCreator
	public DSecond(long value) {
		this();
		this.value = value;
	}

	public static class DSecondDeserializer extends IntegerDeserializer<DSecond> {
		public DSecondDeserializer() {
			super(DSecond.class);
		}

		@Override
		protected DSecond construct() {
			return new DSecond();
		}
	}
}