package j2735.DSRC;

import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonRootName("MessageFrame")
public class EmergencyVehicleAlertMessageFrame extends MessageFrame<EmergencyVehicleAlert> {

	public EmergencyVehicleAlertMessageFrame() {
		super(22, "EmergencyVehicleAlert");
	}

	@Override
	@JsonSerialize(using = EmergencyVehicleAlertMessageFrameValueSerializer.class)
	public EmergencyVehicleAlert getValue() {
		return super.getValue();
	}

	@Override
	@JsonDeserialize(using = EmergencyVehicleAlertMessageFrameValueDeserializer.class)
	public void setValue(EmergencyVehicleAlert value) {
		super.setValue(value);
	}
}