package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class EmergencyDetails extends Asn1Sequence {

	@Asn1Property(tag = 0)
	@JsonDeserialize(using = SSPindex.SSPindexDeserializer.class)
	private SSPindex sspRights;
	@Asn1Property(tag = 1)
	private SirenInUse sirenUse;
	@Asn1Property(tag = 2)
	private LightbarInUse lightsUse;
	@Asn1Property(tag = 3)
	private MultiVehicleResponse multi;
	@Asn1Property(tag = 4, optional = true)
	private PrivilegedEvents events;
	@Asn1Property(tag = 5, optional = true)
	private ResponseType responseType;

	public SSPindex getSspRights() {
		return sspRights;
	}

	public void setSspRights(SSPindex sspRights) {
		this.sspRights = sspRights;
	}

	public SirenInUse getSirenUse() {
		return sirenUse;
	}

	public void setSirenUse(SirenInUse sirenUse) {
		this.sirenUse = sirenUse;
	}

	public LightbarInUse getLightsUse() {
		return lightsUse;
	}

	public void setLightsUse(LightbarInUse lightsUse) {
		this.lightsUse = lightsUse;
	}

	public MultiVehicleResponse getMulti() {
		return multi;
	}

	public void setMulti(MultiVehicleResponse multi) {
		this.multi = multi;
	}

	public PrivilegedEvents getEvents() {
		return events;
	}

	public void setEvents(PrivilegedEvents events) {
		this.events = events;
	}

	public ResponseType getResponseType() {
		return responseType;
	}

	public void setResponseType(ResponseType responseType) {
		this.responseType = responseType;
	}

	EmergencyDetails() {
		super(true);
	}
}