package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import asn2pojo.runtime.annotations.Asn1Property;
import j2735.ITIS.VehicleGroupAffected;
import j2735.ITIS.IncidentResponseEquipment;
import j2735.ITIS.ResponderGroupAffected;
import j2735.REGION.Reg_EmergencyVehicleAlert;
import asn2pojo.runtime.types.Asn1SequenceOf;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 *******************************************************************************
 *
 * This source file was generated by a tool. Beware manual edits might be
 * overwritten in future releases. asn1jvm v1.0-SNAPSHOT
 *
 *******************************************************************************
 * Copyright 2024 USDOT
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class EmergencyVehicleAlert extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	@JsonDeserialize(using = MinuteOfTheYear.MinuteOfTheYearDeserializer.class)
	private MinuteOfTheYear timeStamp;
	@Asn1Property(tag = 1, optional = true)
	private TemporaryID id;
	@Asn1Property(tag = 2)
	private RoadSideAlert rsaMsg;
	@Asn1Property(tag = 3, optional = true)
	private ResponseType responseType;
	@Asn1Property(tag = 4, optional = true)
	private EmergencyDetails details;
	@Asn1Property(tag = 5, optional = true)
	@JsonDeserialize(using = VehicleMass.VehicleMassDeserializer.class)
	private VehicleMass mass;
	@Asn1Property(tag = 6, optional = true)
	private VehicleType basicType;
	@Asn1Property(tag = 7, optional = true)
	private VehicleGroupAffected vehicleType;
	@Asn1Property(tag = 8, optional = true)
	private IncidentResponseEquipment responseEquip;
	@Asn1Property(tag = 9, optional = true)
	private ResponderGroupAffected responderType;
	@Asn1Property(tag = 10, optional = true)
	private SequenceOfRegional regional;

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_EmergencyVehicleAlert> {
		SequenceOfRegional() {
			super(j2735.REGION.Reg_EmergencyVehicleAlert.class, 1L, 4L);
		}
	}

	EmergencyVehicleAlert() {
		super(true);
	}
}