package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import j2735.ITIS.VehicleGroupAffected;
import j2735.ITIS.IncidentResponseEquipment;
import j2735.ITIS.ResponderGroupAffected;
import j2735.REGION.Reg_EmergencyVehicleAlert;
import asn2pojo.runtime.types.Asn1SequenceOf;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class EmergencyVehicleAlert extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	private MinuteOfTheYear timeStamp;
	@Asn1Property(tag = 1, optional = true)
	private TemporaryID id;
	@Asn1Property(tag = 2)
	private RoadSideAlert rsaMsg;
	@Asn1Property(tag = 3, optional = true)
	private ResponseType responseType;
	@Asn1Property(tag = 4, optional = true)
	private EmergencyDetails details;
	@Asn1Property(tag = 5, optional = true)
	private VehicleMass mass;
	@Asn1Property(tag = 6, optional = true)
	private VehicleType basicType;
	@Asn1Property(tag = 7, optional = true)
	private VehicleGroupAffected vehicleType;
	@Asn1Property(tag = 8, optional = true)
	private IncidentResponseEquipment responseEquip;
	@Asn1Property(tag = 9, optional = true)
	private ResponderGroupAffected responderType;
	@Asn1Property(tag = 10, optional = true)
	private SequenceOfRegional regional;

	public MinuteOfTheYear getTimeStamp() {
		return timeStamp;
	}

	public void setTimeStamp(MinuteOfTheYear timeStamp) {
		this.timeStamp = timeStamp;
	}

	public TemporaryID getId() {
		return id;
	}

	public void setId(TemporaryID id) {
		this.id = id;
	}

	public RoadSideAlert getRsaMsg() {
		return rsaMsg;
	}

	public void setRsaMsg(RoadSideAlert rsaMsg) {
		this.rsaMsg = rsaMsg;
	}

	public ResponseType getResponseType() {
		return responseType;
	}

	public void setResponseType(ResponseType responseType) {
		this.responseType = responseType;
	}

	public EmergencyDetails getDetails() {
		return details;
	}

	public void setDetails(EmergencyDetails details) {
		this.details = details;
	}

	public VehicleMass getMass() {
		return mass;
	}

	public void setMass(VehicleMass mass) {
		this.mass = mass;
	}

	public VehicleType getBasicType() {
		return basicType;
	}

	public void setBasicType(VehicleType basicType) {
		this.basicType = basicType;
	}

	public VehicleGroupAffected getVehicleType() {
		return vehicleType;
	}

	public void setVehicleType(VehicleGroupAffected vehicleType) {
		this.vehicleType = vehicleType;
	}

	public IncidentResponseEquipment getResponseEquip() {
		return responseEquip;
	}

	public void setResponseEquip(IncidentResponseEquipment responseEquip) {
		this.responseEquip = responseEquip;
	}

	public ResponderGroupAffected getResponderType() {
		return responderType;
	}

	public void setResponderType(ResponderGroupAffected responderType) {
		this.responderType = responderType;
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_EmergencyVehicleAlert> {
		SequenceOfRegional() {
			super(j2735.REGION.Reg_EmergencyVehicleAlert.class, 1L, 4L);
		}
	}

	public SequenceOfRegional getRegional() {
		return regional;
	}

	public void setRegional(SequenceOfRegional regional) {
		this.regional = regional;
	}

	EmergencyVehicleAlert() {
		super(true);
	}
}