package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import j2735.ITIS.ITIScodes;
import asn2pojo.runtime.annotations.Asn1Property;
import asn2pojo.runtime.types.Asn1SequenceOf;
import j2735.REGION.Reg_EventDescription;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class EventDescription extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private ITIScodes typeEvent;
	@Asn1Property(tag = 1, optional = true)
	private SequenceOfDescription description;
	@Asn1Property(tag = 2, optional = true)
	private Priority priority;
	@Asn1Property(tag = 3, optional = true)
	private HeadingSlice heading;
	@Asn1Property(tag = 4, optional = true)
	private Extent extent;
	@Asn1Property(tag = 5, optional = true)
	private SequenceOfRegional regional;

	public ITIScodes getTypeEvent() {
		return typeEvent;
	}

	public void setTypeEvent(ITIScodes typeEvent) {
		this.typeEvent = typeEvent;
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfDescription extends Asn1SequenceOf<ITIScodes> {
		SequenceOfDescription() {
			super(ITIScodes.class, 1L, 8L);
		}
	}

	public SequenceOfDescription getDescription() {
		return description;
	}

	public void setDescription(SequenceOfDescription description) {
		this.description = description;
	}

	public Priority getPriority() {
		return priority;
	}

	public void setPriority(Priority priority) {
		this.priority = priority;
	}

	public HeadingSlice getHeading() {
		return heading;
	}

	public void setHeading(HeadingSlice heading) {
		this.heading = heading;
	}

	public Extent getExtent() {
		return extent;
	}

	public void setExtent(Extent extent) {
		this.extent = extent;
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_EventDescription> {
		SequenceOfRegional() {
			super(j2735.REGION.Reg_EventDescription.class, 1L, 4L);
		}
	}

	public SequenceOfRegional getRegional() {
		return regional;
	}

	public void setRegional(SequenceOfRegional regional) {
		this.regional = regional;
	}

	EventDescription() {
		super(true);
	}
}