package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Bitstring;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonDeserialize(using = ExteriorLightsDeserializer.class)
public class ExteriorLights extends Asn1Bitstring {

	public boolean isLowBeamHeadlightsOn() {
		return get(0);
	}

	public void setLowBeamHeadlightsOn(boolean lowBeamHeadlightsOn) {
		set(0, lowBeamHeadlightsOn);
	}

	public boolean isHighBeamHeadlightsOn() {
		return get(1);
	}

	public void setHighBeamHeadlightsOn(boolean highBeamHeadlightsOn) {
		set(1, highBeamHeadlightsOn);
	}

	public boolean isLeftTurnSignalOn() {
		return get(2);
	}

	public void setLeftTurnSignalOn(boolean leftTurnSignalOn) {
		set(2, leftTurnSignalOn);
	}

	public boolean isRightTurnSignalOn() {
		return get(3);
	}

	public void setRightTurnSignalOn(boolean rightTurnSignalOn) {
		set(3, rightTurnSignalOn);
	}

	public boolean isHazardSignalOn() {
		return get(4);
	}

	public void setHazardSignalOn(boolean hazardSignalOn) {
		set(4, hazardSignalOn);
	}

	public boolean isAutomaticLightControlOn() {
		return get(5);
	}

	public void setAutomaticLightControlOn(boolean automaticLightControlOn) {
		set(5, automaticLightControlOn);
	}

	public boolean isDaytimeRunningLightsOn() {
		return get(6);
	}

	public void setDaytimeRunningLightsOn(boolean daytimeRunningLightsOn) {
		set(6, daytimeRunningLightsOn);
	}

	public boolean isFogLightOn() {
		return get(7);
	}

	public void setFogLightOn(boolean fogLightOn) {
		set(7, fogLightOn);
	}

	public boolean isParkingLightsOn() {
		return get(8);
	}

	public void setParkingLightsOn(boolean parkingLightsOn) {
		set(8, parkingLightsOn);
	}

	public ExteriorLights() {
		super(9, false,
				new String[]{"lowBeamHeadlightsOn", "highBeamHeadlightsOn", "leftTurnSignalOn", "rightTurnSignalOn",
						"hazardSignalOn", "automaticLightControlOn", "daytimeRunningLightsOn", "fogLightOn",
						"parkingLightsOn"});
	}
}