#!/bin/bash
mkdir subset
cp Angle.java subset
cp Circle.java subset
cp ComputedLane.java subset
cp DYear.java subset
cp DeltaAngle.java subset
cp DescriptiveName.java subset
cp DirectionOfUse.java subset
cp DirectionOfUseDeserializer.java subset
cp DirectionOfUseSerializer.java subset
cp DistanceUnits.java subset
cp DistanceUnitsDeserializer.java subset
cp DistanceUnitsSerializer.java subset
cp DrivenLineOffsetLg.java subset
cp DrivenLineOffsetSm.java subset
cp Elevation.java subset
cp ExitService.java subset
cp ExitServiceSequence.java subset
cp Extent.java subset
cp ExtentDeserializer.java subset
cp ExtentSerializer.java subset
cp FurtherInfoID.java subset
cp GenericSignage.java subset
cp GenericSignageSequence.java subset
cp GeographicalPath.java subset
cp GeometricProjection.java subset
cp HeadingSlice.java subset
cp HeadingSliceDeserializer.java subset
cp ITIStextPhrase.java subset
cp LaneDataAttribute.java subset
cp LaneDataAttributeList.java subset
cp LaneID.java subset
cp LaneWidth.java subset
cp Latitude.java subset
cp Longitude.java subset
cp MUTCDCode.java subset
cp MUTCDCodeDeserializer.java subset
cp MUTCDCodeSerializer.java subset
cp MergeDivergeNodeAngle.java subset
cp MinuteOfTheYear.java subset
cp MinutesDuration.java subset
cp MsgCRC.java subset
cp MsgCount.java subset
cp NodeAttributeLL.java subset
cp NodeAttributeLLDeserializer.java subset
cp NodeAttributeLLList.java subset
cp NodeAttributeLLSerializer.java subset
cp NodeAttributeSetLL.java subset
cp NodeAttributeSetXY.java subset
cp NodeAttributeXY.java subset
cp NodeAttributeXYDeserializer.java subset
cp NodeAttributeXYList.java subset
cp NodeAttributeXYSerializer.java subset
cp NodeLL.java subset
cp NodeListLL.java subset
cp NodeListXY.java subset
cp NodeOffsetPointLL.java subset
cp NodeOffsetPointXY.java subset
cp NodeSetLL.java subset
cp NodeSetXY.java subset
cp NodeXY.java subset
cp Node_LL_24B.java subset
cp Node_LL_28B.java subset
cp Node_LL_32B.java subset
cp Node_LL_36B.java subset
cp Node_LL_44B.java subset
cp Node_LL_48B.java subset
cp Node_LLmD_64b.java subset
cp Node_XY_20b.java subset
cp Node_XY_22b.java subset
cp Node_XY_24b.java subset
cp Node_XY_26b.java subset
cp Node_XY_28b.java subset
cp Node_XY_32b.java subset
cp OffsetLL_B12.java subset
cp OffsetLL_B14.java subset
cp OffsetLL_B16.java subset
cp OffsetLL_B18.java subset
cp OffsetLL_B22.java subset
cp OffsetLL_B24.java subset
cp OffsetSystem.java subset
cp Offset_B10.java subset
cp Offset_B11.java subset
cp Offset_B12.java subset
cp Offset_B13.java subset
cp Offset_B14.java subset
cp Offset_B16.java subset
cp Position3D.java subset
cp Radius_B12.java subset
cp RegionId.java subset
cp RegionList.java subset
cp RegionOffsets.java subset
cp RegionPointSet.java subset
cp RegionalExtension.java subset
cp RegulatorySpeedLimit.java subset
cp RoadRegulatorID.java subset
cp RoadSegmentID.java subset
cp RoadSegmentReferenceID.java subset
cp RoadSignID.java subset
cp RoadwayCrownAngle.java subset
cp SSPindex.java subset
cp Scale_B12.java subset
cp SegmentAttributeLL.java subset
cp SegmentAttributeLLDeserializer.java subset
cp SegmentAttributeLLList.java subset
cp SegmentAttributeLLSerializer.java subset
cp SegmentAttributeXY.java subset
cp SegmentAttributeXYDeserializer.java subset
cp SegmentAttributeXYList.java subset
cp SegmentAttributeXYSerializer.java subset
cp ShapePointSet.java subset
cp SignPrority.java subset
cp SpeedLimit.java subset
cp SpeedLimitList.java subset
cp SpeedLimitSequence.java subset
cp SpeedLimitType.java subset
cp SpeedLimitTypeDeserializer.java subset
cp SpeedLimitTypeSerializer.java subset
cp TravelerDataFrame.java subset
cp TravelerDataFrameList.java subset
cp TravelerInfoType.java subset
cp TravelerInfoTypeDeserializer.java subset
cp TravelerInfoTypeSerializer.java subset
cp TravelerInformation.java subset
cp URL_Base.java subset
cp URL_Short.java subset
cp UniqueMSGID.java subset
cp ValidRegion.java subset
cp Velocity.java subset
cp WorkZone.java subset
cp WorkZoneSequence.java subset
cp Zoom.java subset
