package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Bitstring;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonDeserialize(using = GNSSstatusDeserializer.class)
public class GNSSstatus extends Asn1Bitstring {

	public boolean isUnavailable() {
		return get(0);
	}

	public void setUnavailable(boolean unavailable) {
		set(0, unavailable);
	}

	public boolean isIsHealthy() {
		return get(1);
	}

	public void setIsHealthy(boolean isHealthy) {
		set(1, isHealthy);
	}

	public boolean isIsMonitored() {
		return get(2);
	}

	public void setIsMonitored(boolean isMonitored) {
		set(2, isMonitored);
	}

	public boolean isBaseStationType() {
		return get(3);
	}

	public void setBaseStationType(boolean baseStationType) {
		set(3, baseStationType);
	}

	public boolean isAPDOPofUnder5() {
		return get(4);
	}

	public void setAPDOPofUnder5(boolean aPDOPofUnder5) {
		set(4, aPDOPofUnder5);
	}

	public boolean isInViewOfUnder5() {
		return get(5);
	}

	public void setInViewOfUnder5(boolean inViewOfUnder5) {
		set(5, inViewOfUnder5);
	}

	public boolean isLocalCorrectionsPresent() {
		return get(6);
	}

	public void setLocalCorrectionsPresent(boolean localCorrectionsPresent) {
		set(6, localCorrectionsPresent);
	}

	public boolean isNetworkCorrectionsPresent() {
		return get(7);
	}

	public void setNetworkCorrectionsPresent(boolean networkCorrectionsPresent) {
		set(7, networkCorrectionsPresent);
	}

	public GNSSstatus() {
		super(8, false, new String[]{"unavailable", "isHealthy", "isMonitored", "baseStationType", "aPDOPofUnder5",
				"inViewOfUnder5", "localCorrectionsPresent", "networkCorrectionsPresent"});
	}
}