package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonSerialize(using = HumanPropelledTypeSerializer.class)
@JsonDeserialize(using = HumanPropelledTypeDeserializer.class)
public enum HumanPropelledType implements Asn1Enumerated {
	unavailable(0, "unavailable"), otherTypes(1, "otherTypes"), onFoot(2, "onFoot"), skateboard(3,
			"skateboard"), pushOrKickScooter(4, "pushOrKickScooter"), wheelchair(5, "wheelchair");

	private final int index;
	private final String name;

	public int getIndex() {
		return index;
	}

	public String getName() {
		return name;
	}

	public boolean hasExtensionMarker() {
		return false;
	}

	private HumanPropelledType(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public int maxIndex() {
		return 5;
	}
}