package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class J1939data extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	@JacksonXmlElementWrapper(localName = "tires")
	@JacksonXmlProperty(localName = "TireData")
	private TireDataList tires;
	@Asn1Property(tag = 1, optional = true)
	@JacksonXmlElementWrapper(localName = "axles")
	@JacksonXmlProperty(localName = "AxleWeightSet")
	private AxleWeightList axles;
	@Asn1Property(tag = 2, optional = true)
	@JsonDeserialize(using = TrailerWeight.TrailerWeightDeserializer.class)
	private TrailerWeight trailerWeight;
	@Asn1Property(tag = 3, optional = true)
	@JsonDeserialize(using = CargoWeight.CargoWeightDeserializer.class)
	private CargoWeight cargoWeight;
	@Asn1Property(tag = 4, optional = true)
	@JsonDeserialize(using = SteeringAxleTemperature.SteeringAxleTemperatureDeserializer.class)
	private SteeringAxleTemperature steeringAxleTemperature;
	@Asn1Property(tag = 5, optional = true)
	@JsonDeserialize(using = DriveAxleLocation.DriveAxleLocationDeserializer.class)
	private DriveAxleLocation driveAxleLocation;
	@Asn1Property(tag = 6, optional = true)
	@JsonDeserialize(using = DriveAxleLiftAirPressure.DriveAxleLiftAirPressureDeserializer.class)
	private DriveAxleLiftAirPressure driveAxleLiftAirPressure;
	@Asn1Property(tag = 7, optional = true)
	@JsonDeserialize(using = DriveAxleTemperature.DriveAxleTemperatureDeserializer.class)
	private DriveAxleTemperature driveAxleTemperature;
	@Asn1Property(tag = 8, optional = true)
	@JsonDeserialize(using = DriveAxleLubePressure.DriveAxleLubePressureDeserializer.class)
	private DriveAxleLubePressure driveAxleLubePressure;
	@Asn1Property(tag = 9, optional = true)
	@JsonDeserialize(using = SteeringAxleLubePressure.SteeringAxleLubePressureDeserializer.class)
	private SteeringAxleLubePressure steeringAxleLubePressure;

	public TireDataList getTires() {
		return tires;
	}

	public void setTires(TireDataList tires) {
		this.tires = tires;
	}

	public AxleWeightList getAxles() {
		return axles;
	}

	public void setAxles(AxleWeightList axles) {
		this.axles = axles;
	}

	public TrailerWeight getTrailerWeight() {
		return trailerWeight;
	}

	public void setTrailerWeight(TrailerWeight trailerWeight) {
		this.trailerWeight = trailerWeight;
	}

	public CargoWeight getCargoWeight() {
		return cargoWeight;
	}

	public void setCargoWeight(CargoWeight cargoWeight) {
		this.cargoWeight = cargoWeight;
	}

	public SteeringAxleTemperature getSteeringAxleTemperature() {
		return steeringAxleTemperature;
	}

	public void setSteeringAxleTemperature(SteeringAxleTemperature steeringAxleTemperature) {
		this.steeringAxleTemperature = steeringAxleTemperature;
	}

	public DriveAxleLocation getDriveAxleLocation() {
		return driveAxleLocation;
	}

	public void setDriveAxleLocation(DriveAxleLocation driveAxleLocation) {
		this.driveAxleLocation = driveAxleLocation;
	}

	public DriveAxleLiftAirPressure getDriveAxleLiftAirPressure() {
		return driveAxleLiftAirPressure;
	}

	public void setDriveAxleLiftAirPressure(DriveAxleLiftAirPressure driveAxleLiftAirPressure) {
		this.driveAxleLiftAirPressure = driveAxleLiftAirPressure;
	}

	public DriveAxleTemperature getDriveAxleTemperature() {
		return driveAxleTemperature;
	}

	public void setDriveAxleTemperature(DriveAxleTemperature driveAxleTemperature) {
		this.driveAxleTemperature = driveAxleTemperature;
	}

	public DriveAxleLubePressure getDriveAxleLubePressure() {
		return driveAxleLubePressure;
	}

	public void setDriveAxleLubePressure(DriveAxleLubePressure driveAxleLubePressure) {
		this.driveAxleLubePressure = driveAxleLubePressure;
	}

	public SteeringAxleLubePressure getSteeringAxleLubePressure() {
		return steeringAxleLubePressure;
	}

	public void setSteeringAxleLubePressure(SteeringAxleLubePressure steeringAxleLubePressure) {
		this.steeringAxleLubePressure = steeringAxleLubePressure;
	}

	J1939data() {
		super(true);
	}
}