package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Choice;
import asn2pojo.runtime.annotations.Asn1Property;
import java.util.Optional;
import java.util.List;
import asn2pojo.runtime.types.Asn1Type;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
public class LaneTypeAttributes extends Asn1Choice {

	@Asn1Property(tag = 0)
	private LaneAttributes_Vehicle vehicle;
	@Asn1Property(tag = 1)
	private LaneAttributes_Crosswalk crosswalk;
	@Asn1Property(tag = 2)
	private LaneAttributes_Bike bikeLane;
	@Asn1Property(tag = 3)
	private LaneAttributes_Sidewalk sidewalk;
	@Asn1Property(tag = 4)
	private LaneAttributes_Barrier median;
	@Asn1Property(tag = 5)
	private LaneAttributes_Striping striping;
	@Asn1Property(tag = 6)
	private LaneAttributes_TrackedVehicle trackedVehicle;
	@Asn1Property(tag = 7)
	private LaneAttributes_Parking parking;

	LaneTypeAttributes() {
		super(true);
	}

	public LaneAttributes_Vehicle getVehicle() {
		return vehicle;
	}

	public void setVehicle(LaneAttributes_Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	public LaneAttributes_Crosswalk getCrosswalk() {
		return crosswalk;
	}

	public void setCrosswalk(LaneAttributes_Crosswalk crosswalk) {
		this.crosswalk = crosswalk;
	}

	public LaneAttributes_Bike getBikeLane() {
		return bikeLane;
	}

	public void setBikeLane(LaneAttributes_Bike bikeLane) {
		this.bikeLane = bikeLane;
	}

	public LaneAttributes_Sidewalk getSidewalk() {
		return sidewalk;
	}

	public void setSidewalk(LaneAttributes_Sidewalk sidewalk) {
		this.sidewalk = sidewalk;
	}

	public LaneAttributes_Barrier getMedian() {
		return median;
	}

	public void setMedian(LaneAttributes_Barrier median) {
		this.median = median;
	}

	public LaneAttributes_Striping getStriping() {
		return striping;
	}

	public void setStriping(LaneAttributes_Striping striping) {
		this.striping = striping;
	}

	public LaneAttributes_TrackedVehicle getTrackedVehicle() {
		return trackedVehicle;
	}

	public void setTrackedVehicle(LaneAttributes_TrackedVehicle trackedVehicle) {
		this.trackedVehicle = trackedVehicle;
	}

	public LaneAttributes_Parking getParking() {
		return parking;
	}

	public void setParking(LaneAttributes_Parking parking) {
		this.parking = parking;
	}

	@Override
	protected List<Optional<Asn1Type>> listTypes() {
		return null;
	}
}