package j2735.DSRC;

import asn2pojo.runtime.serialization.BitStringDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class LaneAttributes_SidewalkDeserializer extends BitStringDeserializer<LaneAttributes_Sidewalk> {

	LaneAttributes_SidewalkDeserializer() {
		super(LaneAttributes_Sidewalk.class);
	}

	@Override
	protected LaneAttributes_Sidewalk construct() {
		return new LaneAttributes_Sidewalk();
	}
}