package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Bitstring;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonDeserialize(using = LaneAttributes_ParkingDeserializer.class)
public class LaneAttributes_Parking extends Asn1Bitstring {

	public boolean isParkingRevocableLane() {
		return get(0);
	}

	public void setParkingRevocableLane(boolean parkingRevocableLane) {
		set(0, parkingRevocableLane);
	}

	public boolean isParallelParkingInUse() {
		return get(1);
	}

	public void setParallelParkingInUse(boolean parallelParkingInUse) {
		set(1, parallelParkingInUse);
	}

	public boolean isHeadInParkingInUse() {
		return get(2);
	}

	public void setHeadInParkingInUse(boolean headInParkingInUse) {
		set(2, headInParkingInUse);
	}

	public boolean isDoNotParkZone() {
		return get(3);
	}

	public void setDoNotParkZone(boolean doNotParkZone) {
		set(3, doNotParkZone);
	}

	public boolean isParkingForBusUse() {
		return get(4);
	}

	public void setParkingForBusUse(boolean parkingForBusUse) {
		set(4, parkingForBusUse);
	}

	public boolean isParkingForTaxiUse() {
		return get(5);
	}

	public void setParkingForTaxiUse(boolean parkingForTaxiUse) {
		set(5, parkingForTaxiUse);
	}

	public boolean isNoPublicParkingUse() {
		return get(6);
	}

	public void setNoPublicParkingUse(boolean noPublicParkingUse) {
		set(6, noPublicParkingUse);
	}

	public LaneAttributes_Parking() {
		super(16, false, new String[]{"parkingRevocableLane", "parallelParkingInUse", "headInParkingInUse",
				"doNotParkZone", "parkingForBusUse", "parkingForTaxiUse", "noPublicParkingUse"});
	}
}