package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Bitstring;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonDeserialize(using = LaneAttributes_TrackedVehicleDeserializer.class)
public class LaneAttributes_TrackedVehicle extends Asn1Bitstring {

	public boolean isSpec_RevocableLane() {
		return get(0);
	}

	public void setSpec_RevocableLane(boolean spec_RevocableLane) {
		set(0, spec_RevocableLane);
	}

	public boolean isSpec_commuterRailRoadTrack() {
		return get(1);
	}

	public void setSpec_commuterRailRoadTrack(boolean spec_commuterRailRoadTrack) {
		set(1, spec_commuterRailRoadTrack);
	}

	public boolean isSpec_lightRailRoadTrack() {
		return get(2);
	}

	public void setSpec_lightRailRoadTrack(boolean spec_lightRailRoadTrack) {
		set(2, spec_lightRailRoadTrack);
	}

	public boolean isSpec_heavyRailRoadTrack() {
		return get(3);
	}

	public void setSpec_heavyRailRoadTrack(boolean spec_heavyRailRoadTrack) {
		set(3, spec_heavyRailRoadTrack);
	}

	public boolean isSpec_otherRailType() {
		return get(4);
	}

	public void setSpec_otherRailType(boolean spec_otherRailType) {
		set(4, spec_otherRailType);
	}

	public LaneAttributes_TrackedVehicle() {
		super(16, false, new String[]{"spec-RevocableLane", "spec-commuterRailRoadTrack", "spec-lightRailRoadTrack",
				"spec-heavyRailRoadTrack", "spec-otherRailType"});
	}
}