package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonSerialize(using = LayerTypeSerializer.class)
@JsonDeserialize(using = LayerTypeDeserializer.class)
public enum LayerType implements Asn1Enumerated {
	none(0, "none"), mixedContent(1, "mixedContent"), generalMapData(2, "generalMapData"), intersectionData(3,
			"intersectionData"), curveData(4, "curveData"), roadwaySectionData(5,
					"roadwaySectionData"), parkingAreaData(6, "parkingAreaData"), sharedLaneData(7, "sharedLaneData");

	private final int index;
	private final String name;

	public int getIndex() {
		return index;
	}

	public String getName() {
		return name;
	}

	public boolean hasExtensionMarker() {
		return false;
	}

	private LayerType(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public int maxIndex() {
		return 7;
	}
}