package j2735.DSRC;

import asn2pojo.runtime.serialization.EnumeratedDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class Location_qualityDeserializer extends EnumeratedDeserializer<Location_quality> {

	Location_qualityDeserializer() {
		super(Location_quality.class);
	}

	@Override
	protected Location_quality[] listEnumValues() {
		return Location_quality.values();
	}
}