package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonSerialize(using = Location_qualitySerializer.class)
@JsonDeserialize(using = Location_qualityDeserializer.class)
public enum Location_quality implements Asn1Enumerated {
	loc_qual_bt1m(0, "loc-qual-bt1m"), loc_qual_bt5m(1, "loc-qual-bt5m"), loc_qual_bt12m(2,
			"loc-qual-bt12m"), loc_qual_bt50m(3, "loc-qual-bt50m"), loc_qual_bt125m(4,
					"loc-qual-bt125m"), loc_qual_bt500m(5, "loc-qual-bt500m"), loc_qual_bt1250m(6,
							"loc-qual-bt1250m"), loc_qual_unknown(7, "loc-qual-unknown");

	private final int index;
	private final String name;

	public int getIndex() {
		return index;
	}

	public String getName() {
		return name;
	}

	public boolean hasExtensionMarker() {
		return false;
	}

	private Location_quality(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public int maxIndex() {
		return 7;
	}
}