package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import asn2pojo.runtime.annotations.Asn1Property;
import j2735.REGION.Reg_MapData;
import asn2pojo.runtime.types.Asn1SequenceOf;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

/**
 * 
 *******************************************************************************
 *
 * This source file was generated by a tool. Beware manual edits might be
 * overwritten in future releases. asn1jvm v1.0-SNAPSHOT
 *
 *******************************************************************************
 * Copyright 2024 USDOT
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class MapData extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	@JsonDeserialize(using = MinuteOfTheYear.MinuteOfTheYearDeserializer.class)
	private MinuteOfTheYear timeStamp;
	@Asn1Property(tag = 1)
	@JsonDeserialize(using = MsgCount.MsgCountDeserializer.class)
	private MsgCount msgIssueRevision;
	@Asn1Property(tag = 2, optional = true)
	private LayerType layerType;
	@Asn1Property(tag = 3, optional = true)
	@JsonDeserialize(using = LayerID.LayerIDDeserializer.class)
	private LayerID layerID;
	@Asn1Property(tag = 4, optional = true)
	@JacksonXmlElementWrapper(localName = "intersections")
	@JacksonXmlProperty(localName = "IntersectionGeometry")
	private IntersectionGeometryList intersections;
	@Asn1Property(tag = 5, optional = true)
	@JacksonXmlElementWrapper(localName = "roadSegments")
	@JacksonXmlProperty(localName = "RoadSegment")
	private RoadSegmentList roadSegments;
	@Asn1Property(tag = 6, optional = true)
	private DataParameters dataParameters;
	@Asn1Property(tag = 7, optional = true)
	@JacksonXmlElementWrapper(localName = "restrictionList")
	@JacksonXmlProperty(localName = "RestrictionClassAssignment")
	private RestrictionClassList restrictionList;
	@Asn1Property(tag = 8, optional = true)
	private SequenceOfRegional regional;

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_MapData> {
		SequenceOfRegional() {
			super(j2735.REGION.Reg_MapData.class, 1L, 4L);
		}
	}

	MapData() {
		super(true);
	}
}