package j2735.DSRC;

import asn2pojo.runtime.serialization.IntegerDeserializer;
import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class MergeDivergeNodeAngle extends Asn1Integer {

	public MergeDivergeNodeAngle() {
		super(-180L, 180L);
	}

	@JsonCreator
	public MergeDivergeNodeAngle(long value) {
		this();
		this.value = value;
	}

	public static class MergeDivergeNodeAngleDeserializer extends IntegerDeserializer<MergeDivergeNodeAngle> {

		protected MergeDivergeNodeAngleDeserializer() {
			super(MergeDivergeNodeAngle.class);
		}

		@Override
		protected MergeDivergeNodeAngle construct() {
			return new MergeDivergeNodeAngle();
		}
	}
}