package j2735.DSRC;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
abstract public class MESSAGE_ID_AND_TYPE<T> {

	abstract DSRCmsgID getId();

	abstract Class<T> getType();
}