package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.annotation.JsonProperty;
import j2735.REGION.Reg_MovementState;
import asn2pojo.runtime.types.Asn1SequenceOf;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class MovementState extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	private DescriptiveName movementName;
	@Asn1Property(tag = 1)
	private SignalGroupID signalGroup;
	@Asn1Property(tag = 2, name = "state-time-speed")
	@JsonProperty("state-time-speed")
	@JacksonXmlElementWrapper(localName = "state-time-speed")
	@JacksonXmlProperty(localName = "MovementEvent")
	private MovementEventList state_time_speed;
	@Asn1Property(tag = 3, optional = true)
	@JacksonXmlElementWrapper(localName = "maneuverAssistList")
	@JacksonXmlProperty(localName = "ConnectionManeuverAssist")
	private ManeuverAssistList maneuverAssistList;
	@Asn1Property(tag = 4, optional = true)
	private SequenceOfRegional regional;

	public DescriptiveName getMovementName() {
		return movementName;
	}

	public void setMovementName(DescriptiveName movementName) {
		this.movementName = movementName;
	}

	public SignalGroupID getSignalGroup() {
		return signalGroup;
	}

	public void setSignalGroup(SignalGroupID signalGroup) {
		this.signalGroup = signalGroup;
	}

	public MovementEventList getState_time_speed() {
		return state_time_speed;
	}

	public void setState_time_speed(MovementEventList state_time_speed) {
		this.state_time_speed = state_time_speed;
	}

	public ManeuverAssistList getManeuverAssistList() {
		return maneuverAssistList;
	}

	public void setManeuverAssistList(ManeuverAssistList maneuverAssistList) {
		this.maneuverAssistList = maneuverAssistList;
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_MovementState> {
		SequenceOfRegional() {
			super(j2735.REGION.Reg_MovementState.class, 1L, 4L);
		}
	}

	public SequenceOfRegional getRegional() {
		return regional;
	}

	public void setRegional(SequenceOfRegional regional) {
		this.regional = regional;
	}

	MovementState() {
		super(true);
	}
}