package j2735.DSRC;

import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonRootName("MessageFrame")
public class NMEAcorrectionsMessageFrame extends MessageFrame<NMEAcorrections> {

	public NMEAcorrectionsMessageFrame() {
		super(24, "NMEAcorrections");
	}

	@Override
	@JsonSerialize(using = NMEAcorrectionsMessageFrameValueSerializer.class)
	public NMEAcorrections getValue() {
		return super.getValue();
	}

	@Override
	@JsonDeserialize(using = NMEAcorrectionsMessageFrameValueDeserializer.class)
	public void setValue(NMEAcorrections value) {
		super.setValue(value);
	}
}