package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import asn2pojo.runtime.serialization.IntegerDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class NMEA_MsgType extends Asn1Integer {

	public NMEA_MsgType() {
		super(0L, 32767L);
	}

	@JsonCreator
	public NMEA_MsgType(long value) {
		this();
		this.value = value;
	}

	public static class NMEA_MsgTypeDeserializer extends IntegerDeserializer<NMEA_MsgType> {
		public NMEA_MsgTypeDeserializer() {
			super(NMEA_MsgType.class);
		}

		@Override
		protected NMEA_MsgType construct() {
			return new NMEA_MsgType();
		}
	}
}