package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class PathHistoryPoint extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private OffsetLL_B18 latOffset;
	@Asn1Property(tag = 1)
	private OffsetLL_B18 lonOffset;
	@Asn1Property(tag = 2)
	private VertOffset_B12 elevationOffset;
	@Asn1Property(tag = 3)
	private TimeOffset timeOffset;
	@Asn1Property(tag = 4, optional = true)
	private Speed speed;
	@Asn1Property(tag = 5, optional = true)
	private PositionalAccuracy posAccuracy;
	@Asn1Property(tag = 6, optional = true)
	private CoarseHeading heading;

	public OffsetLL_B18 getLatOffset() {
		return latOffset;
	}

	public void setLatOffset(OffsetLL_B18 latOffset) {
		this.latOffset = latOffset;
	}

	public OffsetLL_B18 getLonOffset() {
		return lonOffset;
	}

	public void setLonOffset(OffsetLL_B18 lonOffset) {
		this.lonOffset = lonOffset;
	}

	public VertOffset_B12 getElevationOffset() {
		return elevationOffset;
	}

	public void setElevationOffset(VertOffset_B12 elevationOffset) {
		this.elevationOffset = elevationOffset;
	}

	public TimeOffset getTimeOffset() {
		return timeOffset;
	}

	public void setTimeOffset(TimeOffset timeOffset) {
		this.timeOffset = timeOffset;
	}

	public Speed getSpeed() {
		return speed;
	}

	public void setSpeed(Speed speed) {
		this.speed = speed;
	}

	public PositionalAccuracy getPosAccuracy() {
		return posAccuracy;
	}

	public void setPosAccuracy(PositionalAccuracy posAccuracy) {
		this.posAccuracy = posAccuracy;
	}

	public CoarseHeading getHeading() {
		return heading;
	}

	public void setHeading(CoarseHeading heading) {
		this.heading = heading;
	}

	PathHistoryPoint() {
		super(true);
	}
}