package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class PathHistory extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	private FullPositionVector initialPosition;
	@Asn1Property(tag = 1, optional = true)
	private GNSSstatus currGNSSstatus;
	@Asn1Property(tag = 2)
	@JacksonXmlElementWrapper(localName = "crumbData")
	@JacksonXmlProperty(localName = "PathHistoryPoint")
	private PathHistoryPointList crumbData;

	public FullPositionVector getInitialPosition() {
		return initialPosition;
	}

	public void setInitialPosition(FullPositionVector initialPosition) {
		this.initialPosition = initialPosition;
	}

	public GNSSstatus getCurrGNSSstatus() {
		return currGNSSstatus;
	}

	public void setCurrGNSSstatus(GNSSstatus currGNSSstatus) {
		this.currGNSSstatus = currGNSSstatus;
	}

	public PathHistoryPointList getCrumbData() {
		return crumbData;
	}

	public void setCrumbData(PathHistoryPointList crumbData) {
		this.crumbData = crumbData;
	}

	PathHistory() {
		super(true);
	}
}