package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Boolean;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonDeserialize(using = PedestrianBicycleDetectDeserializer.class)
public class PedestrianBicycleDetect extends Asn1Boolean {
}