package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import j2735.REGION.Reg_PersonalSafetyMessage;
import asn2pojo.runtime.types.Asn1SequenceOf;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class PersonalSafetyMessage extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private PersonalDeviceUserType basicType;
	@Asn1Property(tag = 1)
	@JsonDeserialize(using = DSecond.DSecondDeserializer.class)
	private DSecond secMark;
	@Asn1Property(tag = 2)
	@JsonDeserialize(using = MsgCount.MsgCountDeserializer.class)
	private MsgCount msgCnt;
	@Asn1Property(tag = 3)
	private TemporaryID id;
	@Asn1Property(tag = 4)
	private Position3D position;
	@Asn1Property(tag = 5)
	private PositionalAccuracy accuracy;
	@Asn1Property(tag = 6)
	@JsonDeserialize(using = Velocity.VelocityDeserializer.class)
	private Velocity speed;
	@Asn1Property(tag = 7)
	@JsonDeserialize(using = Heading.HeadingDeserializer.class)
	private Heading heading;
	@Asn1Property(tag = 8, optional = true)
	private AccelerationSet4Way accelSet;
	@Asn1Property(tag = 9, optional = true)
	private PathHistory pathHistory;
	@Asn1Property(tag = 10, optional = true)
	private PathPrediction pathPrediction;
	@Asn1Property(tag = 11, optional = true)
	private PropelledInformation propulsion;
	@Asn1Property(tag = 12, optional = true)
	private PersonalDeviceUsageState useState;
	@Asn1Property(tag = 13, optional = true)
	private PersonalCrossingRequest crossRequest;
	@Asn1Property(tag = 14, optional = true)
	private PersonalCrossingInProgress crossState;
	@Asn1Property(tag = 15, optional = true)
	private NumberOfParticipantsInCluster clusterSize;
	@Asn1Property(tag = 16, optional = true)
	@JsonDeserialize(using = PersonalClusterRadius.PersonalClusterRadiusDeserializer.class)
	private PersonalClusterRadius clusterRadius;
	@Asn1Property(tag = 17, optional = true)
	private PublicSafetyEventResponderWorkerType eventResponderType;
	@Asn1Property(tag = 18, optional = true)
	private PublicSafetyAndRoadWorkerActivity activityType;
	@Asn1Property(tag = 19, optional = true)
	private PublicSafetyDirectingTrafficSubType activitySubType;
	@Asn1Property(tag = 20, optional = true)
	private PersonalAssistive assistType;
	@Asn1Property(tag = 21, optional = true)
	private UserSizeAndBehaviour sizing;
	@Asn1Property(tag = 22, optional = true)
	private Attachment attachment;
	@Asn1Property(tag = 23, optional = true)
	@JsonDeserialize(using = AttachmentRadius.AttachmentRadiusDeserializer.class)
	private AttachmentRadius attachmentRadius;
	@Asn1Property(tag = 24, optional = true)
	private AnimalType animalType;
	@Asn1Property(tag = 25, optional = true)
	private SequenceOfRegional regional;

	public PersonalDeviceUserType getBasicType() {
		return basicType;
	}

	public void setBasicType(PersonalDeviceUserType basicType) {
		this.basicType = basicType;
	}

	public DSecond getSecMark() {
		return secMark;
	}

	public void setSecMark(DSecond secMark) {
		this.secMark = secMark;
	}

	public MsgCount getMsgCnt() {
		return msgCnt;
	}

	public void setMsgCnt(MsgCount msgCnt) {
		this.msgCnt = msgCnt;
	}

	public TemporaryID getId() {
		return id;
	}

	public void setId(TemporaryID id) {
		this.id = id;
	}

	public Position3D getPosition() {
		return position;
	}

	public void setPosition(Position3D position) {
		this.position = position;
	}

	public PositionalAccuracy getAccuracy() {
		return accuracy;
	}

	public void setAccuracy(PositionalAccuracy accuracy) {
		this.accuracy = accuracy;
	}

	public Velocity getSpeed() {
		return speed;
	}

	public void setSpeed(Velocity speed) {
		this.speed = speed;
	}

	public Heading getHeading() {
		return heading;
	}

	public void setHeading(Heading heading) {
		this.heading = heading;
	}

	public AccelerationSet4Way getAccelSet() {
		return accelSet;
	}

	public void setAccelSet(AccelerationSet4Way accelSet) {
		this.accelSet = accelSet;
	}

	public PathHistory getPathHistory() {
		return pathHistory;
	}

	public void setPathHistory(PathHistory pathHistory) {
		this.pathHistory = pathHistory;
	}

	public PathPrediction getPathPrediction() {
		return pathPrediction;
	}

	public void setPathPrediction(PathPrediction pathPrediction) {
		this.pathPrediction = pathPrediction;
	}

	public PropelledInformation getPropulsion() {
		return propulsion;
	}

	public void setPropulsion(PropelledInformation propulsion) {
		this.propulsion = propulsion;
	}

	public PersonalDeviceUsageState getUseState() {
		return useState;
	}

	public void setUseState(PersonalDeviceUsageState useState) {
		this.useState = useState;
	}

	public PersonalCrossingRequest getCrossRequest() {
		return crossRequest;
	}

	public void setCrossRequest(PersonalCrossingRequest crossRequest) {
		this.crossRequest = crossRequest;
	}

	public PersonalCrossingInProgress getCrossState() {
		return crossState;
	}

	public void setCrossState(PersonalCrossingInProgress crossState) {
		this.crossState = crossState;
	}

	public NumberOfParticipantsInCluster getClusterSize() {
		return clusterSize;
	}

	public void setClusterSize(NumberOfParticipantsInCluster clusterSize) {
		this.clusterSize = clusterSize;
	}

	public PersonalClusterRadius getClusterRadius() {
		return clusterRadius;
	}

	public void setClusterRadius(PersonalClusterRadius clusterRadius) {
		this.clusterRadius = clusterRadius;
	}

	public PublicSafetyEventResponderWorkerType getEventResponderType() {
		return eventResponderType;
	}

	public void setEventResponderType(PublicSafetyEventResponderWorkerType eventResponderType) {
		this.eventResponderType = eventResponderType;
	}

	public PublicSafetyAndRoadWorkerActivity getActivityType() {
		return activityType;
	}

	public void setActivityType(PublicSafetyAndRoadWorkerActivity activityType) {
		this.activityType = activityType;
	}

	public PublicSafetyDirectingTrafficSubType getActivitySubType() {
		return activitySubType;
	}

	public void setActivitySubType(PublicSafetyDirectingTrafficSubType activitySubType) {
		this.activitySubType = activitySubType;
	}

	public PersonalAssistive getAssistType() {
		return assistType;
	}

	public void setAssistType(PersonalAssistive assistType) {
		this.assistType = assistType;
	}

	public UserSizeAndBehaviour getSizing() {
		return sizing;
	}

	public void setSizing(UserSizeAndBehaviour sizing) {
		this.sizing = sizing;
	}

	public Attachment getAttachment() {
		return attachment;
	}

	public void setAttachment(Attachment attachment) {
		this.attachment = attachment;
	}

	public AttachmentRadius getAttachmentRadius() {
		return attachmentRadius;
	}

	public void setAttachmentRadius(AttachmentRadius attachmentRadius) {
		this.attachmentRadius = attachmentRadius;
	}

	public AnimalType getAnimalType() {
		return animalType;
	}

	public void setAnimalType(AnimalType animalType) {
		this.animalType = animalType;
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_PersonalSafetyMessage> {
		SequenceOfRegional() {
			super(j2735.REGION.Reg_PersonalSafetyMessage.class, 1L, 4L);
		}
	}

	public SequenceOfRegional getRegional() {
		return regional;
	}

	public void setRegional(SequenceOfRegional regional) {
		this.regional = regional;
	}

	PersonalSafetyMessage() {
		super(true);
	}
}