package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Bitstring;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonDeserialize(using = PersonalAssistiveDeserializer.class)
public class PersonalAssistive extends Asn1Bitstring {

	public boolean isUnavailable() {
		return get(0);
	}

	public void setUnavailable(boolean unavailable) {
		set(0, unavailable);
	}

	public boolean isOtherType() {
		return get(1);
	}

	public void setOtherType(boolean otherType) {
		set(1, otherType);
	}

	public boolean isVision() {
		return get(2);
	}

	public void setVision(boolean vision) {
		set(2, vision);
	}

	public boolean isHearing() {
		return get(3);
	}

	public void setHearing(boolean hearing) {
		set(3, hearing);
	}

	public boolean isMovement() {
		return get(4);
	}

	public void setMovement(boolean movement) {
		set(4, movement);
	}

	public boolean isCognition() {
		return get(5);
	}

	public void setCognition(boolean cognition) {
		set(5, cognition);
	}

	public PersonalAssistive() {
		super(6, false, new String[]{"unavailable", "otherType", "vision", "hearing", "movement", "cognition"});
	}
}