package j2735.DSRC;

import asn2pojo.runtime.serialization.BitStringDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class PersonalAssistiveDeserializer extends BitStringDeserializer<PersonalAssistive> {

	PersonalAssistiveDeserializer() {
		super(PersonalAssistive.class);
	}

	@Override
	protected PersonalAssistive construct() {
		return new PersonalAssistive();
	}
}