package j2735.DSRC;

import asn2pojo.runtime.annotations.Asn1Property;
import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class PivotPointDescription extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private Offset_B11 pivotOffset;
	@Asn1Property(tag = 1)
	private Angle pivotAngle;
	@Asn1Property(tag = 2)
	private PivotingAllowed pivots;

	public Offset_B11 getPivotOffset() {
		return pivotOffset;
	}

	public void setPivotOffset(Offset_B11 pivotOffset) {
		this.pivotOffset = pivotOffset;
	}

	public Angle getPivotAngle() {
		return pivotAngle;
	}

	public void setPivotAngle(Angle pivotAngle) {
		this.pivotAngle = pivotAngle;
	}

	public PivotingAllowed getPivots() {
		return pivots;
	}

	public void setPivots(PivotingAllowed pivots) {
		this.pivots = pivots;
	}

	PivotPointDescription() {
		super(true);
	}
}