package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonSerialize(using = PositionConfidenceSerializer.class)
@JsonDeserialize(using = PositionConfidenceDeserializer.class)
public enum PositionConfidence implements Asn1Enumerated {
	unavailable(0, "unavailable"), a500m(1, "a500m"), a200m(2, "a200m"), a100m(3, "a100m"), a50m(4, "a50m"), a20m(5,
			"a20m"), a10m(6, "a10m"), a5m(7, "a5m"), a2m(8, "a2m"), a1m(9, "a1m"), a50cm(10, "a50cm"), a20cm(11,
					"a20cm"), a10cm(12, "a10cm"), a5cm(13, "a5cm"), a2cm(14, "a2cm"), a1cm(15, "a1cm");

	private final int index;
	private final String name;

	public int getIndex() {
		return index;
	}

	public String getName() {
		return name;
	}

	public boolean hasExtensionMarker() {
		return false;
	}

	private PositionConfidence(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public int maxIndex() {
		return 15;
	}
}