package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import asn2pojo.runtime.types.Asn1Choice;
import java.util.List;
import java.util.Optional;
import asn2pojo.runtime.types.Asn1Type;
import j2735.REGION.Reg_ProbeDataManagement;
import asn2pojo.runtime.types.Asn1SequenceOf;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class ProbeDataManagement extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	private MinuteOfTheYear timeStamp;
	@Asn1Property(tag = 1)
	private Sample sample;
	@Asn1Property(tag = 2)
	private HeadingSlice directions;
	@Asn1Property(tag = 3)
	private TermChoice term;
	@Asn1Property(tag = 4)
	private SnapshotChoice snapshot;
	@Asn1Property(tag = 5)
	private SecondOfTime txInterval;
	@Asn1Property(tag = 6, optional = true)
	@JacksonXmlElementWrapper(localName = "dataElements")
	@JacksonXmlProperty(localName = "VehicleStatusRequest")
	private VehicleStatusRequestList dataElements;
	@Asn1Property(tag = 7, optional = true)
	private SequenceOfRegional regional;

	public MinuteOfTheYear getTimeStamp() {
		return timeStamp;
	}

	public void setTimeStamp(MinuteOfTheYear timeStamp) {
		this.timeStamp = timeStamp;
	}

	public Sample getSample() {
		return sample;
	}

	public void setSample(Sample sample) {
		this.sample = sample;
	}

	public HeadingSlice getDirections() {
		return directions;
	}

	public void setDirections(HeadingSlice directions) {
		this.directions = directions;
	}

	@JsonInclude(Include.NON_NULL)
	public static class TermChoice extends Asn1Choice {
		@Asn1Property(tag = 0)
		private TermTime termtime;
		@Asn1Property(tag = 1)
		private TermDistance termDistance;

		TermChoice() {
			super(false);
		}

		public TermTime getTermtime() {
			return termtime;
		}

		public void setTermtime(TermTime termtime) {
			this.termtime = termtime;
		}

		public TermDistance getTermDistance() {
			return termDistance;
		}

		public void setTermDistance(TermDistance termDistance) {
			this.termDistance = termDistance;
		}

		@Override
		protected List<Optional<Asn1Type>> listTypes() {
			return null;
		}
	}

	public TermChoice getTerm() {
		return term;
	}

	public void setTerm(TermChoice term) {
		this.term = term;
	}

	@JsonInclude(Include.NON_NULL)
	public static class SnapshotChoice extends Asn1Choice {
		@Asn1Property(tag = 0)
		private SnapshotTime snapshotTime;
		@Asn1Property(tag = 1)
		private SnapshotDistance snapshotDistance;

		SnapshotChoice() {
			super(false);
		}

		public SnapshotTime getSnapshotTime() {
			return snapshotTime;
		}

		public void setSnapshotTime(SnapshotTime snapshotTime) {
			this.snapshotTime = snapshotTime;
		}

		public SnapshotDistance getSnapshotDistance() {
			return snapshotDistance;
		}

		public void setSnapshotDistance(SnapshotDistance snapshotDistance) {
			this.snapshotDistance = snapshotDistance;
		}

		@Override
		protected List<Optional<Asn1Type>> listTypes() {
			return null;
		}
	}

	public SnapshotChoice getSnapshot() {
		return snapshot;
	}

	public void setSnapshot(SnapshotChoice snapshot) {
		this.snapshot = snapshot;
	}

	public SecondOfTime getTxInterval() {
		return txInterval;
	}

	public void setTxInterval(SecondOfTime txInterval) {
		this.txInterval = txInterval;
	}

	public VehicleStatusRequestList getDataElements() {
		return dataElements;
	}

	public void setDataElements(VehicleStatusRequestList dataElements) {
		this.dataElements = dataElements;
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_ProbeDataManagement> {
		SequenceOfRegional() {
			super(j2735.REGION.Reg_ProbeDataManagement.class, 1L, 4L);
		}
	}

	public SequenceOfRegional getRegional() {
		return regional;
	}

	public void setRegional(SequenceOfRegional regional) {
		this.regional = regional;
	}

	ProbeDataManagement() {
		super(true);
	}
}