package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import asn2pojo.runtime.annotations.Asn1Property;
import asn2pojo.runtime.types.Asn1Choice;
import java.util.List;
import java.util.Optional;
import asn2pojo.runtime.types.Asn1Type;
import j2735.REGION.Reg_ProbeDataManagement;
import asn2pojo.runtime.types.Asn1SequenceOf;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

/**
 * 
 *******************************************************************************
 *
 * This source file was generated by a tool. Beware manual edits might be
 * overwritten in future releases. asn1jvm v1.0-SNAPSHOT
 *
 *******************************************************************************
 * Copyright 2024 USDOT
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class ProbeDataManagement extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	@JsonDeserialize(using = MinuteOfTheYear.MinuteOfTheYearDeserializer.class)
	private MinuteOfTheYear timeStamp;
	@Asn1Property(tag = 1)
	private Sample sample;
	@Asn1Property(tag = 2)
	private HeadingSlice directions;
	@Asn1Property(tag = 3)
	private TermChoice term;
	@Asn1Property(tag = 4)
	private SnapshotChoice snapshot;
	@Asn1Property(tag = 5)
	@JsonDeserialize(using = SecondOfTime.SecondOfTimeDeserializer.class)
	private SecondOfTime txInterval;
	@Asn1Property(tag = 6, optional = true)
	@JacksonXmlElementWrapper(localName = "dataElements")
	@JacksonXmlProperty(localName = "VehicleStatusRequest")
	private VehicleStatusRequestList dataElements;
	@Asn1Property(tag = 7, optional = true)
	private SequenceOfRegional regional;

	@Getter
	@Setter
	@JsonInclude(Include.NON_NULL)
	public static class TermChoice extends Asn1Choice {
		@Asn1Property(tag = 0)
		@JsonDeserialize(using = TermTime.TermTimeDeserializer.class)
		private TermTime termtime;
		@Asn1Property(tag = 1)
		@JsonDeserialize(using = TermDistance.TermDistanceDeserializer.class)
		private TermDistance termDistance;

		TermChoice() {
			super(false);
		}

		@Override
		protected List<Optional<Asn1Type>> listTypes() {
			return null;
		}
	}

	@Getter
	@Setter
	@JsonInclude(Include.NON_NULL)
	public static class SnapshotChoice extends Asn1Choice {
		@Asn1Property(tag = 0)
		private SnapshotTime snapshotTime;
		@Asn1Property(tag = 1)
		private SnapshotDistance snapshotDistance;

		SnapshotChoice() {
			super(false);
		}

		@Override
		protected List<Optional<Asn1Type>> listTypes() {
			return null;
		}
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_ProbeDataManagement> {
		SequenceOfRegional() {
			super(j2735.REGION.Reg_ProbeDataManagement.class, 1L, 4L);
		}
	}

	ProbeDataManagement() {
		super(true);
	}
}