package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Bitstring;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonDeserialize(using = PublicSafetyAndRoadWorkerActivityDeserializer.class)
public class PublicSafetyAndRoadWorkerActivity extends Asn1Bitstring {

	public boolean isUnavailable() {
		return get(0);
	}

	public void setUnavailable(boolean unavailable) {
		set(0, unavailable);
	}

	public boolean isWorkingOnRoad() {
		return get(1);
	}

	public void setWorkingOnRoad(boolean workingOnRoad) {
		set(1, workingOnRoad);
	}

	public boolean isSettingUpClosures() {
		return get(2);
	}

	public void setSettingUpClosures(boolean settingUpClosures) {
		set(2, settingUpClosures);
	}

	public boolean isRespondingToEvents() {
		return get(3);
	}

	public void setRespondingToEvents(boolean respondingToEvents) {
		set(3, respondingToEvents);
	}

	public boolean isDirectingTraffic() {
		return get(4);
	}

	public void setDirectingTraffic(boolean directingTraffic) {
		set(4, directingTraffic);
	}

	public boolean isOtherActivities() {
		return get(5);
	}

	public void setOtherActivities(boolean otherActivities) {
		set(5, otherActivities);
	}

	public PublicSafetyAndRoadWorkerActivity() {
		super(6, false, new String[]{"unavailable", "workingOnRoad", "settingUpClosures", "respondingToEvents",
				"directingTraffic", "otherActivities"});
	}
}