package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Bitstring;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonDeserialize(using = PublicSafetyDirectingTrafficSubTypeDeserializer.class)
public class PublicSafetyDirectingTrafficSubType extends Asn1Bitstring {

	public boolean isUnavailable() {
		return get(0);
	}

	public void setUnavailable(boolean unavailable) {
		set(0, unavailable);
	}

	public boolean isPoliceAndTrafficOfficers() {
		return get(1);
	}

	public void setPoliceAndTrafficOfficers(boolean policeAndTrafficOfficers) {
		set(1, policeAndTrafficOfficers);
	}

	public boolean isTrafficControlPersons() {
		return get(2);
	}

	public void setTrafficControlPersons(boolean trafficControlPersons) {
		set(2, trafficControlPersons);
	}

	public boolean isRailroadCrossingGuards() {
		return get(3);
	}

	public void setRailroadCrossingGuards(boolean railroadCrossingGuards) {
		set(3, railroadCrossingGuards);
	}

	public boolean isCivilDefenseNationalGuardMilitaryPolice() {
		return get(4);
	}

	public void setCivilDefenseNationalGuardMilitaryPolice(boolean civilDefenseNationalGuardMilitaryPolice) {
		set(4, civilDefenseNationalGuardMilitaryPolice);
	}

	public boolean isEmergencyOrganizationPersonnel() {
		return get(5);
	}

	public void setEmergencyOrganizationPersonnel(boolean emergencyOrganizationPersonnel) {
		set(5, emergencyOrganizationPersonnel);
	}

	public boolean isHighwayServiceVehiclePersonnel() {
		return get(6);
	}

	public void setHighwayServiceVehiclePersonnel(boolean highwayServiceVehiclePersonnel) {
		set(6, highwayServiceVehiclePersonnel);
	}

	public PublicSafetyDirectingTrafficSubType() {
		super(7, false,
				new String[]{"unavailable", "policeAndTrafficOfficers", "trafficControlPersons",
						"railroadCrossingGuards", "civilDefenseNationalGuardMilitaryPolice",
						"emergencyOrganizationPersonnel", "highwayServiceVehiclePersonnel"});
	}
}