package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import asn2pojo.runtime.serialization.IntegerDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class RadiusOfCurvature extends Asn1Integer {

	public RadiusOfCurvature() {
		super(-32767L, 32767L);
	}

	@JsonCreator
	public RadiusOfCurvature(long value) {
		this();
		this.value = value;
	}

	public static class RadiusOfCurvatureDeserializer extends IntegerDeserializer<RadiusOfCurvature> {
		public RadiusOfCurvatureDeserializer() {
			super(RadiusOfCurvature.class);
		}

		@Override
		protected RadiusOfCurvature construct() {
			return new RadiusOfCurvature();
		}
	}
}