package j2735.DSRC;

import asn2pojo.runtime.annotations.Asn1Property;
import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class RegionOffsets extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private OffsetLL_B16 xOffset;
	@Asn1Property(tag = 1)
	private OffsetLL_B16 yOffset;
	@Asn1Property(tag = 2, optional = true)
	private OffsetLL_B16 zOffset;

	public OffsetLL_B16 getXOffset() {
		return xOffset;
	}

	public void setXOffset(OffsetLL_B16 xOffset) {
		this.xOffset = xOffset;
	}

	public OffsetLL_B16 getYOffset() {
		return yOffset;
	}

	public void setYOffset(OffsetLL_B16 yOffset) {
		this.yOffset = yOffset;
	}

	public OffsetLL_B16 getZOffset() {
		return zOffset;
	}

	public void setZOffset(OffsetLL_B16 zOffset) {
		this.zOffset = zOffset;
	}

	RegionOffsets() {
		super(false);
	}
}