package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class RegulatorySpeedLimit extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private SpeedLimitType type;
	@Asn1Property(tag = 1)
	private Velocity speed;

	public SpeedLimitType getType() {
		return type;
	}

	public void setType(SpeedLimitType type) {
		this.type = type;
	}

	public Velocity getSpeed() {
		return speed;
	}

	public void setSpeed(Velocity speed) {
		this.speed = speed;
	}

	RegulatorySpeedLimit() {
		super(false);
	}
}