package j2735.DSRC;

import asn2pojo.runtime.types.Asn1SequenceOf;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import asn2pojo.runtime.serialization.SequenceOfEnumeratedDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
public class RequestedItemList extends Asn1SequenceOf<RequestedItem> {

	RequestedItemList() {
		super(RequestedItem.class, 1L, 32L);
	}

	public static class RequestedItemListDeserializer
			extends
				SequenceOfEnumeratedDeserializer<RequestedItem, RequestedItemList> {
		public RequestedItemListDeserializer() {
			super(RequestedItemList.class, RequestedItem.class);
		}

		@Override
		protected RequestedItem[] listEnumValues() {
			return RequestedItem.values();
		}

		@Override
		protected RequestedItemList construct() {
			return new RequestedItemList();
		}
	}
}