package j2735.DSRC;

import asn2pojo.runtime.annotations.Asn1Property;
import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class RequestorPositionVector extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private Position3D position;
	@Asn1Property(tag = 1, optional = true)
	private Angle heading;
	@Asn1Property(tag = 2, optional = true)
	private TransmissionAndSpeed speed;

	public Position3D getPosition() {
		return position;
	}

	public void setPosition(Position3D position) {
		this.position = position;
	}

	public Angle getHeading() {
		return heading;
	}

	public void setHeading(Angle heading) {
		this.heading = heading;
	}

	public TransmissionAndSpeed getSpeed() {
		return speed;
	}

	public void setSpeed(TransmissionAndSpeed speed) {
		this.speed = speed;
	}

	RequestorPositionVector() {
		super(true);
	}
}