package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonSerialize(using = RestrictionAppliesToSerializer.class)
@JsonDeserialize(using = RestrictionAppliesToDeserializer.class)
public enum RestrictionAppliesTo implements Asn1Enumerated {
	none(0, "none"), equippedTransit(1, "equippedTransit"), equippedTaxis(2, "equippedTaxis"), equippedOther(3,
			"equippedOther"), emissionCompliant(4, "emissionCompliant"), equippedBicycle(5,
					"equippedBicycle"), weightCompliant(6, "weightCompliant"), heightCompliant(7,
							"heightCompliant"), pedestrians(8, "pedestrians"), slowMovingPersons(9,
									"slowMovingPersons"), wheelchairUsers(10, "wheelchairUsers"), visualDisabilities(11,
											"visualDisabilities"), audioDisabilities(12,
													"audioDisabilities"), otherUnknownDisabilities(13,
															"otherUnknownDisabilities");

	private final int index;
	private final String name;

	public int getIndex() {
		return index;
	}

	public String getName() {
		return name;
	}

	public boolean hasExtensionMarker() {
		return false;
	}

	private RestrictionAppliesTo(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public int maxIndex() {
		return 13;
	}
}