package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class RoadSegmentReferenceID extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	@JsonDeserialize(using = RoadRegulatorID.RoadRegulatorIDDeserializer.class)
	private RoadRegulatorID region;
	@Asn1Property(tag = 1)
	@JsonDeserialize(using = RoadSegmentID.RoadSegmentIDDeserializer.class)
	private RoadSegmentID id;

	public RoadRegulatorID getRegion() {
		return region;
	}

	public void setRegion(RoadRegulatorID region) {
		this.region = region;
	}

	public RoadSegmentID getId() {
		return id;
	}

	public void setId(RoadSegmentID id) {
		this.id = id;
	}

	RoadSegmentReferenceID() {
		super(false);
	}
}