package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import j2735.ITIS.ITIScodes;
import asn2pojo.runtime.types.Asn1SequenceOf;
import j2735.REGION.Reg_RoadSideAlert;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class RoadSideAlert extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private MsgCount msgCnt;
	@Asn1Property(tag = 1, optional = true)
	private MinuteOfTheYear timeStamp;
	@Asn1Property(tag = 2)
	private ITIScodes typeEvent;
	@Asn1Property(tag = 3, optional = true)
	private SequenceOfDescription description;
	@Asn1Property(tag = 4, optional = true)
	private Priority priority;
	@Asn1Property(tag = 5, optional = true)
	private HeadingSlice heading;
	@Asn1Property(tag = 6, optional = true)
	private Extent extent;
	@Asn1Property(tag = 7, optional = true)
	private FullPositionVector position;
	@Asn1Property(tag = 8, optional = true)
	private FurtherInfoID furtherInfoID;
	@Asn1Property(tag = 9, optional = true)
	private SequenceOfRegional regional;

	public MsgCount getMsgCnt() {
		return msgCnt;
	}

	public void setMsgCnt(MsgCount msgCnt) {
		this.msgCnt = msgCnt;
	}

	public MinuteOfTheYear getTimeStamp() {
		return timeStamp;
	}

	public void setTimeStamp(MinuteOfTheYear timeStamp) {
		this.timeStamp = timeStamp;
	}

	public ITIScodes getTypeEvent() {
		return typeEvent;
	}

	public void setTypeEvent(ITIScodes typeEvent) {
		this.typeEvent = typeEvent;
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfDescription extends Asn1SequenceOf<ITIScodes> {
		SequenceOfDescription() {
			super(ITIScodes.class, 1L, 8L);
		}
	}

	public SequenceOfDescription getDescription() {
		return description;
	}

	public void setDescription(SequenceOfDescription description) {
		this.description = description;
	}

	public Priority getPriority() {
		return priority;
	}

	public void setPriority(Priority priority) {
		this.priority = priority;
	}

	public HeadingSlice getHeading() {
		return heading;
	}

	public void setHeading(HeadingSlice heading) {
		this.heading = heading;
	}

	public Extent getExtent() {
		return extent;
	}

	public void setExtent(Extent extent) {
		this.extent = extent;
	}

	public FullPositionVector getPosition() {
		return position;
	}

	public void setPosition(FullPositionVector position) {
		this.position = position;
	}

	public FurtherInfoID getFurtherInfoID() {
		return furtherInfoID;
	}

	public void setFurtherInfoID(FurtherInfoID furtherInfoID) {
		this.furtherInfoID = furtherInfoID;
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_RoadSideAlert> {
		SequenceOfRegional() {
			super(j2735.REGION.Reg_RoadSideAlert.class, 1L, 4L);
		}
	}

	public SequenceOfRegional getRegional() {
		return regional;
	}

	public void setRegional(SequenceOfRegional regional) {
		this.regional = regional;
	}

	RoadSideAlert() {
		super(true);
	}
}