package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import asn2pojo.runtime.annotations.Asn1Property;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class Sample extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private SampleStartInteger sampleStart;
	@Asn1Property(tag = 1)
	private SampleEndInteger sampleEnd;

	public static class SampleStartInteger extends Asn1Integer {
		public SampleStartInteger() {
			super(0L, 255L);
		}

		@JsonCreator
		public SampleStartInteger(long value) {
			this();
			this.value = value;
		}
	}

	public SampleStartInteger getSampleStart() {
		return sampleStart;
	}

	public void setSampleStart(SampleStartInteger sampleStart) {
		this.sampleStart = sampleStart;
	}

	public static class SampleEndInteger extends Asn1Integer {
		public SampleEndInteger() {
			super(0L, 255L);
		}

		@JsonCreator
		public SampleEndInteger(long value) {
			this();
			this.value = value;
		}
	}

	public SampleEndInteger getSampleEnd() {
		return sampleEnd;
	}

	public void setSampleEnd(SampleEndInteger sampleEnd) {
		this.sampleEnd = sampleEnd;
	}

	Sample() {
		super(false);
	}
}