package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class SignalRequesterInfo extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private VehicleID id;
	@Asn1Property(tag = 1)
	@JsonDeserialize(using = RequestID.RequestIDDeserializer.class)
	private RequestID request;
	@Asn1Property(tag = 2)
	@JsonDeserialize(using = MsgCount.MsgCountDeserializer.class)
	private MsgCount sequenceNumber;
	@Asn1Property(tag = 3, optional = true)
	private BasicVehicleRole role;
	@Asn1Property(tag = 4, optional = true)
	private RequestorType typeData;

	public VehicleID getId() {
		return id;
	}

	public void setId(VehicleID id) {
		this.id = id;
	}

	public RequestID getRequest() {
		return request;
	}

	public void setRequest(RequestID request) {
		this.request = request;
	}

	public MsgCount getSequenceNumber() {
		return sequenceNumber;
	}

	public void setSequenceNumber(MsgCount sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}

	public BasicVehicleRole getRole() {
		return role;
	}

	public void setRole(BasicVehicleRole role) {
		this.role = role;
	}

	public RequestorType getTypeData() {
		return typeData;
	}

	public void setTypeData(RequestorType typeData) {
		this.typeData = typeData;
	}

	SignalRequesterInfo() {
		super(true);
	}
}