package j2735.DSRC;

import asn2pojo.runtime.annotations.Asn1Property;
import asn2pojo.runtime.types.Asn1Sequence;
import asn2pojo.runtime.types.Asn1SequenceOf;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import j2735.REGION.Reg_SignalRequestPackage;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class SignalRequestPackage extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private SignalRequest request;
	@Asn1Property(tag = 1, optional = true)
	private MinuteOfTheYear minute;
	@Asn1Property(tag = 2, optional = true)
	private DSecond second;
	@Asn1Property(tag = 3, optional = true)
	private DSecond duration;
	@Asn1Property(tag = 4, optional = true)
	private SequenceOfRegional regional;

	public SignalRequest getRequest() {
		return request;
	}

	public void setRequest(SignalRequest request) {
		this.request = request;
	}

	public MinuteOfTheYear getMinute() {
		return minute;
	}

	public void setMinute(MinuteOfTheYear minute) {
		this.minute = minute;
	}

	public DSecond getSecond() {
		return second;
	}

	public void setSecond(DSecond second) {
		this.second = second;
	}

	public DSecond getDuration() {
		return duration;
	}

	public void setDuration(DSecond duration) {
		this.duration = duration;
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_SignalRequestPackage> {
		SequenceOfRegional() {
			super(Reg_SignalRequestPackage.class, 1L, 4L);
		}
	}

	public SequenceOfRegional getRegional() {
		return regional;
	}

	public void setRegional(SequenceOfRegional regional) {
		this.regional = regional;
	}

	SignalRequestPackage() {
		super(true);
	}
}