package j2735.DSRC;

import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonRootName("MessageFrame")
public class SignalStatusMessageMessageFrame extends MessageFrame<SignalStatusMessage> {

	public SignalStatusMessageMessageFrame() {
		super(30, "SignalStatusMessage");
	}

	@Override
	@JsonSerialize(using = SignalStatusMessageMessageFrameValueSerializer.class)
	public SignalStatusMessage getValue() {
		return super.getValue();
	}

	@Override
	@JsonDeserialize(using = SignalStatusMessageMessageFrameValueDeserializer.class)
	public void setValue(SignalStatusMessage value) {
		super.setValue(value);
	}
}