package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import j2735.REGION.Reg_SignalStatus;
import asn2pojo.runtime.types.Asn1SequenceOf;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class SignalStatus extends Asn1Sequence {

	@Asn1Property(tag = 0)
	@JsonDeserialize(using = MsgCount.MsgCountDeserializer.class)
	private MsgCount sequenceNumber;
	@Asn1Property(tag = 1)
	private IntersectionReferenceID id;
	@Asn1Property(tag = 2)
	@JacksonXmlElementWrapper(localName = "sigStatus")
	@JacksonXmlProperty(localName = "SignalStatusPackage")
	private SignalStatusPackageList sigStatus;
	@Asn1Property(tag = 3, optional = true)
	private SequenceOfRegional regional;

	public MsgCount getSequenceNumber() {
		return sequenceNumber;
	}

	public void setSequenceNumber(MsgCount sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}

	public IntersectionReferenceID getId() {
		return id;
	}

	public void setId(IntersectionReferenceID id) {
		this.id = id;
	}

	public SignalStatusPackageList getSigStatus() {
		return sigStatus;
	}

	public void setSigStatus(SignalStatusPackageList sigStatus) {
		this.sigStatus = sigStatus;
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_SignalStatus> {
		SequenceOfRegional() {
			super(j2735.REGION.Reg_SignalStatus.class, 1L, 4L);
		}
	}

	public SequenceOfRegional getRegional() {
		return regional;
	}

	public void setRegional(SequenceOfRegional regional) {
		this.regional = regional;
	}

	SignalStatus() {
		super(true);
	}
}