package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class Snapshot extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private FullPositionVector thePosition;
	@Asn1Property(tag = 1, optional = true)
	private VehicleSafetyExtensions safetyExt;
	@Asn1Property(tag = 2, optional = true)
	private VehicleStatus dataSet;

	public FullPositionVector getThePosition() {
		return thePosition;
	}

	public void setThePosition(FullPositionVector thePosition) {
		this.thePosition = thePosition;
	}

	public VehicleSafetyExtensions getSafetyExt() {
		return safetyExt;
	}

	public void setSafetyExt(VehicleSafetyExtensions safetyExt) {
		this.safetyExt = safetyExt;
	}

	public VehicleStatus getDataSet() {
		return dataSet;
	}

	public void setDataSet(VehicleStatus dataSet) {
		this.dataSet = dataSet;
	}

	Snapshot() {
		super(true);
	}
}