package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class SnapshotTime extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private GrossSpeed speed1;
	@Asn1Property(tag = 1)
	private SecondOfTime time1;
	@Asn1Property(tag = 2)
	private GrossSpeed speed2;
	@Asn1Property(tag = 3)
	private SecondOfTime time2;

	public GrossSpeed getSpeed1() {
		return speed1;
	}

	public void setSpeed1(GrossSpeed speed1) {
		this.speed1 = speed1;
	}

	public SecondOfTime getTime1() {
		return time1;
	}

	public void setTime1(SecondOfTime time1) {
		this.time1 = time1;
	}

	public GrossSpeed getSpeed2() {
		return speed2;
	}

	public void setSpeed2(GrossSpeed speed2) {
		this.speed2 = speed2;
	}

	public SecondOfTime getTime2() {
		return time2;
	}

	public void setTime2(SecondOfTime time2) {
		this.time2 = time2;
	}

	SnapshotTime() {
		super(false);
	}
}