package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class SnapshotDistance extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private GrossDistance distance1;
	@Asn1Property(tag = 1)
	private GrossSpeed speed1;
	@Asn1Property(tag = 2)
	private GrossDistance distance2;
	@Asn1Property(tag = 3)
	private GrossSpeed speed2;

	public GrossDistance getDistance1() {
		return distance1;
	}

	public void setDistance1(GrossDistance distance1) {
		this.distance1 = distance1;
	}

	public GrossSpeed getSpeed1() {
		return speed1;
	}

	public void setSpeed1(GrossSpeed speed1) {
		this.speed1 = speed1;
	}

	public GrossDistance getDistance2() {
		return distance2;
	}

	public void setDistance2(GrossDistance distance2) {
		this.distance2 = distance2;
	}

	public GrossSpeed getSpeed2() {
		return speed2;
	}

	public void setSpeed2(GrossSpeed speed2) {
		this.speed2 = speed2;
	}

	SnapshotDistance() {
		super(false);
	}
}