package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class SpeedandHeadingandThrottleConfidence extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private HeadingConfidence heading;
	@Asn1Property(tag = 1)
	private SpeedConfidence speed;
	@Asn1Property(tag = 2)
	private ThrottleConfidence throttle;

	public HeadingConfidence getHeading() {
		return heading;
	}

	public void setHeading(HeadingConfidence heading) {
		this.heading = heading;
	}

	public SpeedConfidence getSpeed() {
		return speed;
	}

	public void setSpeed(SpeedConfidence speed) {
		this.speed = speed;
	}

	public ThrottleConfidence getThrottle() {
		return throttle;
	}

	public void setThrottle(ThrottleConfidence throttle) {
		this.throttle = throttle;
	}

	SpeedandHeadingandThrottleConfidence() {
		super(false);
	}
}