package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class SpeedProfile extends Asn1Sequence {

	@Asn1Property(tag = 0)
	@JacksonXmlElementWrapper(localName = "speedReports")
	@JacksonXmlProperty(localName = "SpeedProfileMeasurement")
	private SpeedProfileMeasurementList speedReports;

	public SpeedProfileMeasurementList getSpeedReports() {
		return speedReports;
	}

	public void setSpeedReports(SpeedProfileMeasurementList speedReports) {
		this.speedReports = speedReports;
	}

	SpeedProfile() {
		super(true);
	}
}