package j2735.DSRC;

import asn2pojo.runtime.annotations.Asn1Property;
import asn2pojo.runtime.types.Asn1Sequence;
import asn2pojo.runtime.types.Asn1SequenceOf;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import j2735.REGION.Reg_SupplementalVehicleExtensions;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class SupplementalVehicleExtensions extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	private BasicVehicleClass classification;
	@Asn1Property(tag = 1, optional = true)
	private VehicleClassification classDetails;
	@Asn1Property(tag = 2, optional = true)
	private VehicleData vehicleData;
	@Asn1Property(tag = 3, optional = true)
	private WeatherReport weatherReport;
	@Asn1Property(tag = 4, optional = true)
	private WeatherProbe weatherProbe;
	@Asn1Property(tag = 5, optional = true)
	private ObstacleDetection obstacle;
	@Asn1Property(tag = 6, optional = true)
	private DisabledVehicle status;
	@Asn1Property(tag = 7, optional = true)
	private SpeedProfile speedProfile;
	@Asn1Property(tag = 8, optional = true)
	private RTCMPackage theRTCM;
	@Asn1Property(tag = 9, optional = true)
	private SequenceOfRegional regional;

	public BasicVehicleClass getClassification() {
		return classification;
	}

	public void setClassification(BasicVehicleClass classification) {
		this.classification = classification;
	}

	public VehicleClassification getClassDetails() {
		return classDetails;
	}

	public void setClassDetails(VehicleClassification classDetails) {
		this.classDetails = classDetails;
	}

	public VehicleData getVehicleData() {
		return vehicleData;
	}

	public void setVehicleData(VehicleData vehicleData) {
		this.vehicleData = vehicleData;
	}

	public WeatherReport getWeatherReport() {
		return weatherReport;
	}

	public void setWeatherReport(WeatherReport weatherReport) {
		this.weatherReport = weatherReport;
	}

	public WeatherProbe getWeatherProbe() {
		return weatherProbe;
	}

	public void setWeatherProbe(WeatherProbe weatherProbe) {
		this.weatherProbe = weatherProbe;
	}

	public ObstacleDetection getObstacle() {
		return obstacle;
	}

	public void setObstacle(ObstacleDetection obstacle) {
		this.obstacle = obstacle;
	}

	public DisabledVehicle getStatus() {
		return status;
	}

	public void setStatus(DisabledVehicle status) {
		this.status = status;
	}

	public SpeedProfile getSpeedProfile() {
		return speedProfile;
	}

	public void setSpeedProfile(SpeedProfile speedProfile) {
		this.speedProfile = speedProfile;
	}

	public RTCMPackage getTheRTCM() {
		return theRTCM;
	}

	public void setTheRTCM(RTCMPackage theRTCM) {
		this.theRTCM = theRTCM;
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_SupplementalVehicleExtensions> {
		SequenceOfRegional() {
			super(Reg_SupplementalVehicleExtensions.class, 1L, 4L);
		}
	}

	public SequenceOfRegional getRegional() {
		return regional;
	}

	public void setRegional(SequenceOfRegional regional) {
		this.regional = regional;
	}

	SupplementalVehicleExtensions() {
		super(true);
	}
}