package j2735.DSRC;

import com.fasterxml.jackson.annotation.JsonRootName;
import j2735.DSRC.BSMpartIIExtension;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonRootName("BSMpartIIExtension")
public class SupplementalVehicleExtensionsBSMpartIIExtension extends BSMpartIIExtension<SupplementalVehicleExtensions> {

	public SupplementalVehicleExtensionsBSMpartIIExtension() {
		super(2, "SupplementalVehicleExtensions");
	}

	@Override
	@JsonSerialize(using = SupplementalVehicleExtensionsBSMpartIIExtensionValueSerializer.class)
	public SupplementalVehicleExtensions getPartII_Value() {
		return super.getPartII_Value();
	}

	@Override
	@JsonDeserialize(using = SupplementalVehicleExtensionsBSMpartIIExtensionValueDeserializer.class)
	public void setPartII_Value(SupplementalVehicleExtensions value) {
		super.setPartII_Value(value);
	}
}