package j2735.DSRC;

import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonRootName("MessageFrame")
public class TestMessage15MessageFrame extends MessageFrame<TestMessage15> {

	public TestMessage15MessageFrame() {
		super(255, "TestMessage15");
	}

	@Override
	@JsonSerialize(using = TestMessage15MessageFrameValueSerializer.class)
	public TestMessage15 getValue() {
		return super.getValue();
	}

	@Override
	@JsonDeserialize(using = TestMessage15MessageFrameValueDeserializer.class)
	public void setValue(TestMessage15 value) {
		super.setValue(value);
	}
}