package j2735.DSRC;

import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonRootName("MessageFrame")
public class TestMessage05MessageFrame extends MessageFrame<TestMessage05> {

	public TestMessage05MessageFrame() {
		super(245, "TestMessage05");
	}

	@Override
	@JsonSerialize(using = TestMessage05MessageFrameValueSerializer.class)
	public TestMessage05 getValue() {
		return super.getValue();
	}

	@Override
	@JsonDeserialize(using = TestMessage05MessageFrameValueDeserializer.class)
	public void setValue(TestMessage05 value) {
		super.setValue(value);
	}
}