package j2735.DSRC;

import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonRootName("MessageFrame")
public class TestMessage03MessageFrame extends MessageFrame<TestMessage03> {

	public TestMessage03MessageFrame() {
		super(243, "TestMessage03");
	}

	@Override
	@JsonSerialize(using = TestMessage03MessageFrameValueSerializer.class)
	public TestMessage03 getValue() {
		return super.getValue();
	}

	@Override
	@JsonDeserialize(using = TestMessage03MessageFrameValueDeserializer.class)
	public void setValue(TestMessage03 value) {
		super.setValue(value);
	}
}