package j2735.DSRC;

import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonRootName("MessageFrame")
public class TestMessage08MessageFrame extends MessageFrame<TestMessage08> {

	public TestMessage08MessageFrame() {
		super(248, "TestMessage08");
	}

	@Override
	@JsonSerialize(using = TestMessage08MessageFrameValueSerializer.class)
	public TestMessage08 getValue() {
		return super.getValue();
	}

	@Override
	@JsonDeserialize(using = TestMessage08MessageFrameValueDeserializer.class)
	public void setValue(TestMessage08 value) {
		super.setValue(value);
	}
}