package j2735.DSRC;

import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonRootName("MessageFrame")
public class TestMessage00MessageFrame extends MessageFrame<TestMessage00> {

	public TestMessage00MessageFrame() {
		super(240, "TestMessage00");
	}

	@Override
	@JsonSerialize(using = TestMessage00MessageFrameValueSerializer.class)
	public TestMessage00 getValue() {
		return super.getValue();
	}

	@Override
	@JsonDeserialize(using = TestMessage00MessageFrameValueDeserializer.class)
	public void setValue(TestMessage00 value) {
		super.setValue(value);
	}
}