package j2735.DSRC;

import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonRootName("MessageFrame")
public class TestMessage13MessageFrame extends MessageFrame<TestMessage13> {

	public TestMessage13MessageFrame() {
		super(253, "TestMessage13");
	}

	@Override
	@JsonSerialize(using = TestMessage13MessageFrameValueSerializer.class)
	public TestMessage13 getValue() {
		return super.getValue();
	}

	@Override
	@JsonDeserialize(using = TestMessage13MessageFrameValueDeserializer.class)
	public void setValue(TestMessage13 value) {
		super.setValue(value);
	}
}