package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import asn2pojo.runtime.serialization.IntegerDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class TimeMark extends Asn1Integer {

	public TimeMark() {
		super(0L, 36001L);
	}

	@JsonCreator
	public TimeMark(long value) {
		this();
		this.value = value;
	}

	public static class TimeMarkDeserializer extends IntegerDeserializer<TimeMark> {
		public TimeMarkDeserializer() {
			super(TimeMark.class);
		}

		@Override
		protected TimeMark construct() {
			return new TimeMark();
		}
	}
}