package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import asn2pojo.runtime.serialization.IntegerDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class TireTemp extends Asn1Integer {

	public TireTemp() {
		super(-8736L, 55519L);
	}

	@JsonCreator
	public TireTemp(long value) {
		this();
		this.value = value;
	}

	public static class TireTempDeserializer extends IntegerDeserializer<TireTemp> {
		public TireTempDeserializer() {
			super(TireTemp.class);
		}

		@Override
		protected TireTemp construct() {
			return new TireTemp();
		}
	}
}