package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class TireData extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	private TireLocation location;
	@Asn1Property(tag = 1, optional = true)
	private TirePressure pressure;
	@Asn1Property(tag = 2, optional = true)
	private TireTemp temp;
	@Asn1Property(tag = 3, optional = true)
	private WheelSensorStatus wheelSensorStatus;
	@Asn1Property(tag = 4, optional = true)
	private WheelEndElectFault wheelEndElectFault;
	@Asn1Property(tag = 5, optional = true)
	private TireLeakageRate leakageRate;
	@Asn1Property(tag = 6, optional = true)
	private TirePressureThresholdDetection detection;

	public TireLocation getLocation() {
		return location;
	}

	public void setLocation(TireLocation location) {
		this.location = location;
	}

	public TirePressure getPressure() {
		return pressure;
	}

	public void setPressure(TirePressure pressure) {
		this.pressure = pressure;
	}

	public TireTemp getTemp() {
		return temp;
	}

	public void setTemp(TireTemp temp) {
		this.temp = temp;
	}

	public WheelSensorStatus getWheelSensorStatus() {
		return wheelSensorStatus;
	}

	public void setWheelSensorStatus(WheelSensorStatus wheelSensorStatus) {
		this.wheelSensorStatus = wheelSensorStatus;
	}

	public WheelEndElectFault getWheelEndElectFault() {
		return wheelEndElectFault;
	}

	public void setWheelEndElectFault(WheelEndElectFault wheelEndElectFault) {
		this.wheelEndElectFault = wheelEndElectFault;
	}

	public TireLeakageRate getLeakageRate() {
		return leakageRate;
	}

	public void setLeakageRate(TireLeakageRate leakageRate) {
		this.leakageRate = leakageRate;
	}

	public TirePressureThresholdDetection getDetection() {
		return detection;
	}

	public void setDetection(TirePressureThresholdDetection detection) {
		this.detection = detection;
	}

	TireData() {
		super(true);
	}
}