package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonSerialize(using = TirePressureThresholdDetectionSerializer.class)
@JsonDeserialize(using = TirePressureThresholdDetectionDeserializer.class)
public enum TirePressureThresholdDetection implements Asn1Enumerated {
	noData(0, "noData"), overPressure(1, "overPressure"), noWarningPressure(2, "noWarningPressure"), underPressure(3,
			"underPressure"), extremeUnderPressure(4, "extremeUnderPressure"), undefined(5,
					"undefined"), errorIndicator(6, "errorIndicator"), notAvailable(7, "notAvailable");

	private final int index;
	private final String name;

	public int getIndex() {
		return index;
	}

	public String getName() {
		return name;
	}

	public boolean hasExtensionMarker() {
		return false;
	}

	private TirePressureThresholdDetection(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public int maxIndex() {
		return 7;
	}
}