package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class TrailerHistoryPoint extends Asn1Sequence {

	@Asn1Property(tag = 0)
	@JsonDeserialize(using = Angle.AngleDeserializer.class)
	private Angle pivotAngle;
	@Asn1Property(tag = 1)
	@JsonDeserialize(using = TimeOffset.TimeOffsetDeserializer.class)
	private TimeOffset timeOffset;
	@Asn1Property(tag = 2)
	private Node_XY_24b positionOffset;
	@Asn1Property(tag = 3, optional = true)
	@JsonDeserialize(using = VertOffset_B07.VertOffset_B07Deserializer.class)
	private VertOffset_B07 elevationOffset;
	@Asn1Property(tag = 4, optional = true)
	@JsonDeserialize(using = CoarseHeading.CoarseHeadingDeserializer.class)
	private CoarseHeading heading;

	public Angle getPivotAngle() {
		return pivotAngle;
	}

	public void setPivotAngle(Angle pivotAngle) {
		this.pivotAngle = pivotAngle;
	}

	public TimeOffset getTimeOffset() {
		return timeOffset;
	}

	public void setTimeOffset(TimeOffset timeOffset) {
		this.timeOffset = timeOffset;
	}

	public Node_XY_24b getPositionOffset() {
		return positionOffset;
	}

	public void setPositionOffset(Node_XY_24b positionOffset) {
		this.positionOffset = positionOffset;
	}

	public VertOffset_B07 getElevationOffset() {
		return elevationOffset;
	}

	public void setElevationOffset(VertOffset_B07 elevationOffset) {
		this.elevationOffset = elevationOffset;
	}

	public CoarseHeading getHeading() {
		return heading;
	}

	public void setHeading(CoarseHeading heading) {
		this.heading = heading;
	}

	TrailerHistoryPoint() {
		super(true);
	}
}