package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

/**
 * 
 *******************************************************************************
 *
 * This source file was generated by a tool. Beware manual edits might be
 * overwritten in future releases. asn1jvm v1.0-SNAPSHOT
 *
 *******************************************************************************
 * Copyright 2024 USDOT
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class TrailerUnitDescription extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private IsDolly isDolly;
	@Asn1Property(tag = 1)
	@JsonDeserialize(using = VehicleWidth.VehicleWidthDeserializer.class)
	private VehicleWidth width;
	@Asn1Property(tag = 2)
	@JsonDeserialize(using = VehicleLength.VehicleLengthDeserializer.class)
	private VehicleLength length;
	@Asn1Property(tag = 3, optional = true)
	@JsonDeserialize(using = VehicleHeight.VehicleHeightDeserializer.class)
	private VehicleHeight height;
	@Asn1Property(tag = 4, optional = true)
	@JsonDeserialize(using = TrailerMass.TrailerMassDeserializer.class)
	private TrailerMass mass;
	@Asn1Property(tag = 5, optional = true)
	private BumperHeights bumperHeights;
	@Asn1Property(tag = 6, optional = true)
	@JsonDeserialize(using = VehicleHeight.VehicleHeightDeserializer.class)
	private VehicleHeight centerOfGravity;
	@Asn1Property(tag = 7)
	private PivotPointDescription frontPivot;
	@Asn1Property(tag = 8, optional = true)
	private PivotPointDescription rearPivot;
	@Asn1Property(tag = 9, optional = true)
	@JsonDeserialize(using = Offset_B12.Offset_B12Deserializer.class)
	private Offset_B12 rearWheelOffset;
	@Asn1Property(tag = 10)
	private Node_XY_24b positionOffset;
	@Asn1Property(tag = 11, optional = true)
	@JsonDeserialize(using = VertOffset_B07.VertOffset_B07Deserializer.class)
	private VertOffset_B07 elevationOffset;
	@Asn1Property(tag = 12, optional = true)
	@JacksonXmlElementWrapper(localName = "crumbData")
	@JacksonXmlProperty(localName = "TrailerHistoryPoint")
	private TrailerHistoryPointList crumbData;

	TrailerUnitDescription() {
		super(true);
	}
}