package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import asn2pojo.runtime.serialization.IntegerDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class TrailerMass extends Asn1Integer {

	public TrailerMass() {
		super(0L, 255L);
	}

	@JsonCreator
	public TrailerMass(long value) {
		this();
		this.value = value;
	}

	public static class TrailerMassDeserializer extends IntegerDeserializer<TrailerMass> {
		public TrailerMassDeserializer() {
			super(TrailerMass.class);
		}

		@Override
		protected TrailerMass construct() {
			return new TrailerMass();
		}
	}
}