package j2735.DSRC;

import asn2pojo.runtime.annotations.Asn1Property;
import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class TrailerData extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private SSPindex sspRights;
	@Asn1Property(tag = 1)
	private PivotPointDescription connection;
	@Asn1Property(tag = 2)
	@JacksonXmlElementWrapper(localName = "units")
	@JacksonXmlProperty(localName = "TrailerUnitDescription")
	private TrailerUnitDescriptionList units;

	public SSPindex getSspRights() {
		return sspRights;
	}

	public void setSspRights(SSPindex sspRights) {
		this.sspRights = sspRights;
	}

	public PivotPointDescription getConnection() {
		return connection;
	}

	public void setConnection(PivotPointDescription connection) {
		this.connection = connection;
	}

	public TrailerUnitDescriptionList getUnits() {
		return units;
	}

	public void setUnits(TrailerUnitDescriptionList units) {
		this.units = units;
	}

	TrailerData() {
		super(true);
	}
}