package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonSerialize(using = TransmissionStateSerializer.class)
@JsonDeserialize(using = TransmissionStateDeserializer.class)
public enum TransmissionState implements Asn1Enumerated {
	neutral(0, "neutral"), park(1, "park"), forwardGears(2, "forwardGears"), reverseGears(3, "reverseGears"), reserved1(
			4, "reserved1"), reserved2(5, "reserved2"), reserved3(6, "reserved3"), unavailable(7, "unavailable");

	private final int index;
	private final String name;

	public int getIndex() {
		return index;
	}

	public String getName() {
		return name;
	}

	public boolean hasExtensionMarker() {
		return false;
	}

	private TransmissionState(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public int maxIndex() {
		return 7;
	}
}