package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Bitstring;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonDeserialize(using = TransitStatusDeserializer.class)
public class TransitStatus extends Asn1Bitstring {

	public boolean isNone() {
		return get(0);
	}

	public void setNone(boolean none) {
		set(0, none);
	}

	public boolean isAnADAuse() {
		return get(1);
	}

	public void setAnADAuse(boolean anADAuse) {
		set(1, anADAuse);
	}

	public boolean isABikeLoad() {
		return get(2);
	}

	public void setABikeLoad(boolean aBikeLoad) {
		set(2, aBikeLoad);
	}

	public boolean isDoorOpen() {
		return get(3);
	}

	public void setDoorOpen(boolean doorOpen) {
		set(3, doorOpen);
	}

	public boolean isOccM() {
		return get(4);
	}

	public void setOccM(boolean occM) {
		set(4, occM);
	}

	public boolean isOccL() {
		return get(5);
	}

	public void setOccL(boolean occL) {
		set(5, occL);
	}

	public TransitStatus() {
		super(6, false, new String[]{"none", "anADAuse", "aBikeLoad", "doorOpen", "occM", "occL"});
	}
}