package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Bitstring;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonDeserialize(using = TransitVehicleStatusDeserializer.class)
public class TransitVehicleStatus extends Asn1Bitstring {

	public boolean isLoading() {
		return get(0);
	}

	public void setLoading(boolean loading) {
		set(0, loading);
	}

	public boolean isAnADAuse() {
		return get(1);
	}

	public void setAnADAuse(boolean anADAuse) {
		set(1, anADAuse);
	}

	public boolean isABikeLoad() {
		return get(2);
	}

	public void setABikeLoad(boolean aBikeLoad) {
		set(2, aBikeLoad);
	}

	public boolean isDoorOpen() {
		return get(3);
	}

	public void setDoorOpen(boolean doorOpen) {
		set(3, doorOpen);
	}

	public boolean isCharging() {
		return get(4);
	}

	public void setCharging(boolean charging) {
		set(4, charging);
	}

	public boolean isAtStopLine() {
		return get(5);
	}

	public void setAtStopLine(boolean atStopLine) {
		set(5, atStopLine);
	}

	public TransitVehicleStatus() {
		super(8, false, new String[]{"loading", "anADAuse", "aBikeLoad", "doorOpen", "charging", "atStopLine"});
	}
}