package j2735.DSRC;

import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonRootName("MessageFrame")
public class TravelerInformationMessageFrame extends MessageFrame<TravelerInformation> {

	public TravelerInformationMessageFrame() {
		super(31, "TravelerInformation");
	}

	@Override
	@JsonSerialize(using = TravelerInformationMessageFrameValueSerializer.class)
	public TravelerInformation getValue() {
		return super.getValue();
	}

	@Override
	@JsonDeserialize(using = TravelerInformationMessageFrameValueDeserializer.class)
	public void setValue(TravelerInformation value) {
		super.setValue(value);
	}
}