package j2735.DSRC;

import asn2pojo.runtime.types.IA5String;
import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class URL_Link extends IA5String {

	public URL_Link() {
		super(1, 255);
	}

	@JsonCreator
	public URL_Link(String value) {
		this();
		this.value = value;
	}
}