package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Bitstring;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonDeserialize(using = UserSizeAndBehaviourDeserializer.class)
public class UserSizeAndBehaviour extends Asn1Bitstring {

	public boolean isUnavailable() {
		return get(0);
	}

	public void setUnavailable(boolean unavailable) {
		set(0, unavailable);
	}

	public boolean isSmallStature() {
		return get(1);
	}

	public void setSmallStature(boolean smallStature) {
		set(1, smallStature);
	}

	public boolean isLargeStature() {
		return get(2);
	}

	public void setLargeStature(boolean largeStature) {
		set(2, largeStature);
	}

	public boolean isErraticMoving() {
		return get(3);
	}

	public void setErraticMoving(boolean erraticMoving) {
		set(3, erraticMoving);
	}

	public boolean isSlowMoving() {
		return get(4);
	}

	public void setSlowMoving(boolean slowMoving) {
		set(4, slowMoving);
	}

	public UserSizeAndBehaviour() {
		super(5, false, new String[]{"unavailable", "smallStature", "largeStature", "erraticMoving", "slowMoving"});
	}
}