package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class VehicleSize extends Asn1Sequence {

	@Asn1Property(tag = 0)
	@JsonDeserialize(using = VehicleWidth.VehicleWidthDeserializer.class)
	private VehicleWidth width;
	@Asn1Property(tag = 1)
	@JsonDeserialize(using = VehicleLength.VehicleLengthDeserializer.class)
	private VehicleLength length;

	public VehicleWidth getWidth() {
		return width;
	}

	public void setWidth(VehicleWidth width) {
		this.width = width;
	}

	public VehicleLength getLength() {
		return length;
	}

	public void setLength(VehicleLength length) {
		this.length = length;
	}

	VehicleSize() {
		super(false);
	}
}