package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import asn2pojo.runtime.types.Asn1Boolean;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class VehicleStatusRequest extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private VehicleStatusDeviceTypeTag dataType;
	@Asn1Property(tag = 1, optional = true)
	private SubTypeInteger subType;
	@Asn1Property(tag = 2, optional = true)
	private SendOnLessThenValueInteger sendOnLessThenValue;
	@Asn1Property(tag = 3, optional = true)
	private SendOnMoreThenValueInteger sendOnMoreThenValue;
	@Asn1Property(tag = 4, optional = true)
	private Asn1Boolean sendAll;

	public VehicleStatusDeviceTypeTag getDataType() {
		return dataType;
	}

	public void setDataType(VehicleStatusDeviceTypeTag dataType) {
		this.dataType = dataType;
	}

	public static class SubTypeInteger extends Asn1Integer {
		public SubTypeInteger() {
			super(1L, 15L);
		}

		@JsonCreator
		public SubTypeInteger(long value) {
			this();
			this.value = value;
		}
	}

	public SubTypeInteger getSubType() {
		return subType;
	}

	public void setSubType(SubTypeInteger subType) {
		this.subType = subType;
	}

	public static class SendOnLessThenValueInteger extends Asn1Integer {
		public SendOnLessThenValueInteger() {
			super(-32767L, 32767L);
		}

		@JsonCreator
		public SendOnLessThenValueInteger(long value) {
			this();
			this.value = value;
		}
	}

	public SendOnLessThenValueInteger getSendOnLessThenValue() {
		return sendOnLessThenValue;
	}

	public void setSendOnLessThenValue(SendOnLessThenValueInteger sendOnLessThenValue) {
		this.sendOnLessThenValue = sendOnLessThenValue;
	}

	public static class SendOnMoreThenValueInteger extends Asn1Integer {
		public SendOnMoreThenValueInteger() {
			super(-32767L, 32767L);
		}

		@JsonCreator
		public SendOnMoreThenValueInteger(long value) {
			this();
			this.value = value;
		}
	}

	public SendOnMoreThenValueInteger getSendOnMoreThenValue() {
		return sendOnMoreThenValue;
	}

	public void setSendOnMoreThenValue(SendOnMoreThenValueInteger sendOnMoreThenValue) {
		this.sendOnMoreThenValue = sendOnMoreThenValue;
	}

	public Asn1Boolean getSendAll() {
		return sendAll;
	}

	public void setSendAll(Asn1Boolean sendAll) {
		this.sendAll = sendAll;
	}

	VehicleStatusRequest() {
		super(true);
	}
}