package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonSerialize(using = VehicleTypeSerializer.class)
@JsonDeserialize(using = VehicleTypeDeserializer.class)
public enum VehicleType implements Asn1Enumerated {
	none(0, "none"), unknown(1, "unknown"), special(2, "special"), moto(3, "moto"), car(4, "car"), carOther(5,
			"carOther"), bus(6, "bus"), axleCnt2(7, "axleCnt2"), axleCnt3(8, "axleCnt3"), axleCnt4(9,
					"axleCnt4"), axleCnt4Trailer(10, "axleCnt4Trailer"), axleCnt5Trailer(11,
							"axleCnt5Trailer"), axleCnt6Trailer(12, "axleCnt6Trailer"), axleCnt5MultiTrailer(13,
									"axleCnt5MultiTrailer"), axleCnt6MultiTrailer(14,
											"axleCnt6MultiTrailer"), axleCnt7MultiTrailer(15, "axleCnt7MultiTrailer");

	private final int index;
	private final String name;

	public int getIndex() {
		return index;
	}

	public String getName() {
		return name;
	}

	public boolean hasExtensionMarker() {
		return false;
	}

	private VehicleType(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public int maxIndex() {
		return 15;
	}
}