package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Bitstring;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonDeserialize(using = VehicleEventFlagsDeserializer.class)
public class VehicleEventFlags extends Asn1Bitstring {

	public boolean isEventHazardLights() {
		return get(0);
	}

	public void setEventHazardLights(boolean eventHazardLights) {
		set(0, eventHazardLights);
	}

	public boolean isEventStopLineViolation() {
		return get(1);
	}

	public void setEventStopLineViolation(boolean eventStopLineViolation) {
		set(1, eventStopLineViolation);
	}

	public boolean isEventABSactivated() {
		return get(2);
	}

	public void setEventABSactivated(boolean eventABSactivated) {
		set(2, eventABSactivated);
	}

	public boolean isEventTractionControlLoss() {
		return get(3);
	}

	public void setEventTractionControlLoss(boolean eventTractionControlLoss) {
		set(3, eventTractionControlLoss);
	}

	public boolean isEventStabilityControlactivated() {
		return get(4);
	}

	public void setEventStabilityControlactivated(boolean eventStabilityControlactivated) {
		set(4, eventStabilityControlactivated);
	}

	public boolean isEventHazardousMaterials() {
		return get(5);
	}

	public void setEventHazardousMaterials(boolean eventHazardousMaterials) {
		set(5, eventHazardousMaterials);
	}

	public boolean isEventReserved1() {
		return get(6);
	}

	public void setEventReserved1(boolean eventReserved1) {
		set(6, eventReserved1);
	}

	public boolean isEventHardBraking() {
		return get(7);
	}

	public void setEventHardBraking(boolean eventHardBraking) {
		set(7, eventHardBraking);
	}

	public boolean isEventLightsChanged() {
		return get(8);
	}

	public void setEventLightsChanged(boolean eventLightsChanged) {
		set(8, eventLightsChanged);
	}

	public boolean isEventWipersChanged() {
		return get(9);
	}

	public void setEventWipersChanged(boolean eventWipersChanged) {
		set(9, eventWipersChanged);
	}

	public boolean isEventFlatTire() {
		return get(10);
	}

	public void setEventFlatTire(boolean eventFlatTire) {
		set(10, eventFlatTire);
	}

	public boolean isEventDisabledVehicle() {
		return get(11);
	}

	public void setEventDisabledVehicle(boolean eventDisabledVehicle) {
		set(11, eventDisabledVehicle);
	}

	public boolean isEventAirBagDeployment() {
		return get(12);
	}

	public void setEventAirBagDeployment(boolean eventAirBagDeployment) {
		set(12, eventAirBagDeployment);
	}

	public VehicleEventFlags() {
		super(13, false,
				new String[]{"eventHazardLights", "eventStopLineViolation", "eventABSactivated",
						"eventTractionControlLoss", "eventStabilityControlactivated", "eventHazardousMaterials",
						"eventReserved1", "eventHardBraking", "eventLightsChanged", "eventWipersChanged",
						"eventFlatTire", "eventDisabledVehicle", "eventAirBagDeployment"});
	}
}