package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import j2735.ITIS.VehicleGroupAffected;
import j2735.ITIS.IncidentResponseEquipment;
import j2735.ITIS.ResponderGroupAffected;
import j2735.REGION.Reg_VehicleClassification;
import asn2pojo.runtime.types.Asn1SequenceOf;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class VehicleClassification extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	private BasicVehicleClass keyType;
	@Asn1Property(tag = 1, optional = true)
	private BasicVehicleRole role;
	@Asn1Property(tag = 2, optional = true)
	private Iso3833VehicleType iso3883;
	@Asn1Property(tag = 3, optional = true)
	private VehicleType hpmsType;
	@Asn1Property(tag = 4, optional = true)
	private VehicleGroupAffected vehicleType;
	@Asn1Property(tag = 5, optional = true)
	private IncidentResponseEquipment responseEquip;
	@Asn1Property(tag = 6, optional = true)
	private ResponderGroupAffected responderType;
	@Asn1Property(tag = 7, optional = true)
	private FuelType fuelType;
	@Asn1Property(tag = 8, optional = true)
	private SequenceOfRegional regional;

	public BasicVehicleClass getKeyType() {
		return keyType;
	}

	public void setKeyType(BasicVehicleClass keyType) {
		this.keyType = keyType;
	}

	public BasicVehicleRole getRole() {
		return role;
	}

	public void setRole(BasicVehicleRole role) {
		this.role = role;
	}

	public Iso3833VehicleType getIso3883() {
		return iso3883;
	}

	public void setIso3883(Iso3833VehicleType iso3883) {
		this.iso3883 = iso3883;
	}

	public VehicleType getHpmsType() {
		return hpmsType;
	}

	public void setHpmsType(VehicleType hpmsType) {
		this.hpmsType = hpmsType;
	}

	public VehicleGroupAffected getVehicleType() {
		return vehicleType;
	}

	public void setVehicleType(VehicleGroupAffected vehicleType) {
		this.vehicleType = vehicleType;
	}

	public IncidentResponseEquipment getResponseEquip() {
		return responseEquip;
	}

	public void setResponseEquip(IncidentResponseEquipment responseEquip) {
		this.responseEquip = responseEquip;
	}

	public ResponderGroupAffected getResponderType() {
		return responderType;
	}

	public void setResponderType(ResponderGroupAffected responderType) {
		this.responderType = responderType;
	}

	public FuelType getFuelType() {
		return fuelType;
	}

	public void setFuelType(FuelType fuelType) {
		this.fuelType = fuelType;
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_VehicleClassification> {
		SequenceOfRegional() {
			super(j2735.REGION.Reg_VehicleClassification.class, 1L, 4L);
		}
	}

	public SequenceOfRegional getRegional() {
		return regional;
	}

	public void setRegional(SequenceOfRegional regional) {
		this.regional = regional;
	}

	VehicleClassification() {
		super(true);
	}
}