package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class VehicleData extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	@JsonDeserialize(using = VehicleHeight.VehicleHeightDeserializer.class)
	private VehicleHeight height;
	@Asn1Property(tag = 1, optional = true)
	private BumperHeights bumpers;
	@Asn1Property(tag = 2, optional = true)
	@JsonDeserialize(using = VehicleMass.VehicleMassDeserializer.class)
	private VehicleMass mass;
	@Asn1Property(tag = 3, optional = true)
	@JsonDeserialize(using = TrailerWeight.TrailerWeightDeserializer.class)
	private TrailerWeight trailerWeight;

	public VehicleHeight getHeight() {
		return height;
	}

	public void setHeight(VehicleHeight height) {
		this.height = height;
	}

	public BumperHeights getBumpers() {
		return bumpers;
	}

	public void setBumpers(BumperHeights bumpers) {
		this.bumpers = bumpers;
	}

	public VehicleMass getMass() {
		return mass;
	}

	public void setMass(VehicleMass mass) {
		this.mass = mass;
	}

	public TrailerWeight getTrailerWeight() {
		return trailerWeight;
	}

	public void setTrailerWeight(TrailerWeight trailerWeight) {
		this.trailerWeight = trailerWeight;
	}

	VehicleData() {
		super(true);
	}
}