package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonSerialize(using = VehicleStatusDeviceTypeTagSerializer.class)
@JsonDeserialize(using = VehicleStatusDeviceTypeTagDeserializer.class)
public enum VehicleStatusDeviceTypeTag implements Asn1Enumerated {
	unknown(0, "unknown"), lights(1, "lights"), wipers(2, "wipers"), brakes(3, "brakes"), stab(4, "stab"), trac(5,
			"trac"), abs(6, "abs"), sunS(7, "sunS"), rainS(8, "rainS"), airTemp(9, "airTemp"), steering(10,
					"steering"), vertAccelThres(11, "vertAccelThres"), vertAccel(12, "vertAccel"), hozAccelLong(13,
							"hozAccelLong"), hozAccelLat(14, "hozAccelLat"), hozAccelCon(15, "hozAccelCon"), accel4way(
									16, "accel4way"), confidenceSet(17, "confidenceSet"), obDist(18,
											"obDist"), obDirect(19, "obDirect"), yaw(20, "yaw"), yawRateCon(21,
													"yawRateCon"), dateTime(22, "dateTime"), fullPos(23,
															"fullPos"), position2D(24, "position2D"), position3D(25,
																	"position3D"), vehicle(26, "vehicle"), speedHeadC(
																			27, "speedHeadC"), speedC(28, "speedC");

	private final int index;
	private final String name;

	public int getIndex() {
		return index;
	}

	public String getName() {
		return name;
	}

	public boolean hasExtensionMarker() {
		return false;
	}

	private VehicleStatusDeviceTypeTag(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public int maxIndex() {
		return 28;
	}
}