package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class VehicleSafetyExtensions extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	private VehicleEventFlags events;
	@Asn1Property(tag = 1, optional = true)
	private PathHistory pathHistory;
	@Asn1Property(tag = 2, optional = true)
	private PathPrediction pathPrediction;
	@Asn1Property(tag = 3, optional = true)
	private ExteriorLights lights;

	public VehicleEventFlags getEvents() {
		return events;
	}

	public void setEvents(VehicleEventFlags events) {
		this.events = events;
	}

	public PathHistory getPathHistory() {
		return pathHistory;
	}

	public void setPathHistory(PathHistory pathHistory) {
		this.pathHistory = pathHistory;
	}

	public PathPrediction getPathPrediction() {
		return pathPrediction;
	}

	public void setPathPrediction(PathPrediction pathPrediction) {
		this.pathPrediction = pathPrediction;
	}

	public ExteriorLights getLights() {
		return lights;
	}

	public void setLights(ExteriorLights lights) {
		this.lights = lights;
	}

	VehicleSafetyExtensions() {
		super(true);
	}
}