package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import asn2pojo.runtime.serialization.IntegerDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class VertOffset_B10 extends Asn1Integer {

	public VertOffset_B10() {
		super(-512L, 511L);
	}

	@JsonCreator
	public VertOffset_B10(long value) {
		this();
		this.value = value;
	}

	public static class VertOffset_B10Deserializer extends IntegerDeserializer<VertOffset_B10> {
		public VertOffset_B10Deserializer() {
			super(VertOffset_B10.class);
		}

		@Override
		protected VertOffset_B10 construct() {
			return new VertOffset_B10();
		}
	}
}