package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import asn2pojo.runtime.serialization.IntegerDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class VertOffset_B08 extends Asn1Integer {

	public VertOffset_B08() {
		super(-128L, 127L);
	}

	@JsonCreator
	public VertOffset_B08(long value) {
		this();
		this.value = value;
	}

	public static class VertOffset_B08Deserializer extends IntegerDeserializer<VertOffset_B08> {
		public VertOffset_B08Deserializer() {
			super(VertOffset_B08.class);
		}

		@Override
		protected VertOffset_B08 construct() {
			return new VertOffset_B08();
		}
	}
}