package j2735.DSRC;

import asn2pojo.runtime.annotations.Asn1Property;
import asn2pojo.runtime.types.Asn1Choice;
import asn2pojo.runtime.types.Asn1Type;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import j2735.REGION.Reg_VerticalOffset;

import java.util.List;
import java.util.Optional;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
public class VerticalOffset extends Asn1Choice {

	@Asn1Property(tag = 0)
	private VertOffset_B07 offset1;
	@Asn1Property(tag = 1)
	private VertOffset_B08 offset2;
	@Asn1Property(tag = 2)
	private VertOffset_B09 offset3;
	@Asn1Property(tag = 3)
	private VertOffset_B10 offset4;
	@Asn1Property(tag = 4)
	private VertOffset_B11 offset5;
	@Asn1Property(tag = 5)
	private VertOffset_B12 offset6;
	@Asn1Property(tag = 6)
	private Elevation elevation;
	@Asn1Property(tag = 7)
	private Reg_VerticalOffset regional;

	VerticalOffset() {
		super(false);
	}

	public VertOffset_B07 getOffset1() {
		return offset1;
	}

	public void setOffset1(VertOffset_B07 offset1) {
		this.offset1 = offset1;
	}

	public VertOffset_B08 getOffset2() {
		return offset2;
	}

	public void setOffset2(VertOffset_B08 offset2) {
		this.offset2 = offset2;
	}

	public VertOffset_B09 getOffset3() {
		return offset3;
	}

	public void setOffset3(VertOffset_B09 offset3) {
		this.offset3 = offset3;
	}

	public VertOffset_B10 getOffset4() {
		return offset4;
	}

	public void setOffset4(VertOffset_B10 offset4) {
		this.offset4 = offset4;
	}

	public VertOffset_B11 getOffset5() {
		return offset5;
	}

	public void setOffset5(VertOffset_B11 offset5) {
		this.offset5 = offset5;
	}

	public VertOffset_B12 getOffset6() {
		return offset6;
	}

	public void setOffset6(VertOffset_B12 offset6) {
		this.offset6 = offset6;
	}

	public Elevation getElevation() {
		return elevation;
	}

	public void setElevation(Elevation elevation) {
		this.elevation = elevation;
	}

	public Reg_VerticalOffset getRegional() {
		return regional;
	}

	public void setRegional(Reg_VerticalOffset regional) {
		this.regional = regional;
	}

	@Override
	protected List<Optional<Asn1Type>> listTypes() {
		return null;
	}
}