package j2735.DSRC;

import asn2pojo.runtime.annotations.Asn1Property;
import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import j2735.NTCIP.*;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class WeatherReport extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private EssPrecipYesNo isRaining;
	@Asn1Property(tag = 1, optional = true)
	private EssPrecipRate rainRate;
	@Asn1Property(tag = 2, optional = true)
	private EssPrecipSituation precipSituation;
	@Asn1Property(tag = 3, optional = true)
	private EssSolarRadiation solarRadiation;
	@Asn1Property(tag = 4, optional = true)
	private EssMobileFriction friction;
	@Asn1Property(tag = 5, optional = true)
	private CoefficientOfFriction roadFriction;

	public EssPrecipYesNo getIsRaining() {
		return isRaining;
	}

	public void setIsRaining(EssPrecipYesNo isRaining) {
		this.isRaining = isRaining;
	}

	public EssPrecipRate getRainRate() {
		return rainRate;
	}

	public void setRainRate(EssPrecipRate rainRate) {
		this.rainRate = rainRate;
	}

	public EssPrecipSituation getPrecipSituation() {
		return precipSituation;
	}

	public void setPrecipSituation(EssPrecipSituation precipSituation) {
		this.precipSituation = precipSituation;
	}

	public EssSolarRadiation getSolarRadiation() {
		return solarRadiation;
	}

	public void setSolarRadiation(EssSolarRadiation solarRadiation) {
		this.solarRadiation = solarRadiation;
	}

	public EssMobileFriction getFriction() {
		return friction;
	}

	public void setFriction(EssMobileFriction friction) {
		this.friction = friction;
	}

	public CoefficientOfFriction getRoadFriction() {
		return roadFriction;
	}

	public void setRoadFriction(CoefficientOfFriction roadFriction) {
		this.roadFriction = roadFriction;
	}

	WeatherReport() {
		super(true);
	}
}