package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import asn2pojo.runtime.serialization.IntegerDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class WiperRate extends Asn1Integer {

	public WiperRate() {
		super(0L, 127L);
	}

	@JsonCreator
	public WiperRate(long value) {
		this();
		this.value = value;
	}

	public static class WiperRateDeserializer extends IntegerDeserializer<WiperRate> {
		public WiperRateDeserializer() {
			super(WiperRate.class);
		}

		@Override
		protected WiperRate construct() {
			return new WiperRate();
		}
	}
}