package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class WiperSet extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private WiperStatus statusFront;
	@Asn1Property(tag = 1)
	private WiperRate rateFront;
	@Asn1Property(tag = 2, optional = true)
	private WiperStatus statusRear;
	@Asn1Property(tag = 3, optional = true)
	private WiperRate rateRear;

	public WiperStatus getStatusFront() {
		return statusFront;
	}

	public void setStatusFront(WiperStatus statusFront) {
		this.statusFront = statusFront;
	}

	public WiperRate getRateFront() {
		return rateFront;
	}

	public void setRateFront(WiperRate rateFront) {
		this.rateFront = rateFront;
	}

	public WiperStatus getStatusRear() {
		return statusRear;
	}

	public void setStatusRear(WiperStatus statusRear) {
		this.statusRear = statusRear;
	}

	public WiperRate getRateRear() {
		return rateRear;
	}

	public void setRateRear(WiperRate rateRear) {
		this.rateRear = rateRear;
	}

	WiperSet() {
		super(false);
	}
}