package j2735.DSRC;

import asn2pojo.runtime.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonSerialize(using = YawRateConfidenceSerializer.class)
@JsonDeserialize(using = YawRateConfidenceDeserializer.class)
public enum YawRateConfidence implements Asn1Enumerated {
	unavailable(0, "unavailable"), degSec_100_00(1, "degSec-100-00"), degSec_010_00(2, "degSec-010-00"), degSec_005_00(
			3, "degSec-005-00"), degSec_001_00(4, "degSec-001-00"), degSec_000_10(5,
					"degSec-000-10"), degSec_000_05(6, "degSec-000-05"), degSec_000_01(7, "degSec-000-01");

	private final int index;
	private final String name;

	public int getIndex() {
		return index;
	}

	public String getName() {
		return name;
	}

	public boolean hasExtensionMarker() {
		return false;
	}

	private YawRateConfidence(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public int maxIndex() {
		return 7;
	}
}