package j2735.AddGrpB;

import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import asn2pojo.runtime.serialization.IntegerDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class LongitudeDMS extends Asn1Integer {

	public LongitudeDMS() {
		super(-64800000L, 64800000L);
	}

	@JsonCreator
	public LongitudeDMS(long value) {
		this();
		this.value = value;
	}

	public static class LongitudeDMSDeserializer extends IntegerDeserializer<LongitudeDMS> {
		public LongitudeDMSDeserializer() {
			super(LongitudeDMS.class);
		}

		@Override
		protected LongitudeDMS construct() {
			return new LongitudeDMS();
		}
	}
}