package j2735.AddGrpB;

import asn2pojo.runtime.annotations.Asn1Property;
import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class LongitudeDMS2 extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private DegreesLong d;
	@Asn1Property(tag = 1)
	private MinutesAngle m;
	@Asn1Property(tag = 2)
	private SecondsAngle s;

	public DegreesLong getD() {
		return d;
	}

	public void setD(DegreesLong d) {
		this.d = d;
	}

	public MinutesAngle getM() {
		return m;
	}

	public void setM(MinutesAngle m) {
		this.m = m;
	}

	public SecondsAngle getS() {
		return s;
	}

	public void setS(SecondsAngle s) {
		this.s = s;
	}

	LongitudeDMS2() {
		super(false);
	}
}