package j2735.AddGrpB;

import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import asn2pojo.runtime.serialization.IntegerDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class MinutesAngle extends Asn1Integer {

	public MinutesAngle() {
		super(0L, 59L);
	}

	@JsonCreator
	public MinutesAngle(long value) {
		this();
		this.value = value;
	}

	public static class MinutesAngleDeserializer extends IntegerDeserializer<MinutesAngle> {
		public MinutesAngleDeserializer() {
			super(MinutesAngle.class);
		}

		@Override
		protected MinutesAngle construct() {
			return new MinutesAngle();
		}
	}
}