package j2735.AddGrpB;

import asn2pojo.runtime.serialization.OpenTypeSerializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class MovementEvent_addGrpBReg_MovementEventValueSerializer extends OpenTypeSerializer<MovementEvent_addGrpB> {

	public MovementEvent_addGrpBReg_MovementEventValueSerializer() {
		super(MovementEvent_addGrpB.class, "regExtValue", "MovementEvent_addGrpB");
	}
}