package j2735.AddGrpB;

import com.fasterxml.jackson.annotation.JsonRootName;
import j2735.REGION.Reg_MovementEvent;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonRootName("Reg_MovementEvent")
public class MovementEvent_addGrpBReg_MovementEvent extends Reg_MovementEvent<MovementEvent_addGrpB> {

	public MovementEvent_addGrpBReg_MovementEvent() {
		super(2, "MovementEvent_addGrpB");
	}

	@Override
	@JsonSerialize(using = MovementEvent_addGrpBReg_MovementEventValueSerializer.class)
	public MovementEvent_addGrpB getRegExtValue() {
		return super.getRegExtValue();
	}

	@Override
	@JsonDeserialize(using = MovementEvent_addGrpBReg_MovementEventValueDeserializer.class)
	public void setRegExtValue(MovementEvent_addGrpB value) {
		super.setRegExtValue(value);
	}
}