package j2735.AddGrpB;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class TimeMark extends Asn1Sequence {

	@Asn1Property(tag = 0)
	@JsonDeserialize(using = Year.YearDeserializer.class)
	private Year year;
	@Asn1Property(tag = 1)
	@JsonDeserialize(using = Month.MonthDeserializer.class)
	private Month month;
	@Asn1Property(tag = 2)
	@JsonDeserialize(using = Day.DayDeserializer.class)
	private Day day;
	@Asn1Property(tag = 3)
	private SummerTime summerTime;
	@Asn1Property(tag = 4)
	private Holiday holiday;
	@Asn1Property(tag = 5)
	private DayOfWeek dayofWeek;
	@Asn1Property(tag = 6)
	@JsonDeserialize(using = Hour.HourDeserializer.class)
	private Hour hour;
	@Asn1Property(tag = 7)
	@JsonDeserialize(using = Minute.MinuteDeserializer.class)
	private Minute minute;
	@Asn1Property(tag = 8)
	@JsonDeserialize(using = Second.SecondDeserializer.class)
	private Second second;
	@Asn1Property(tag = 9)
	@JsonDeserialize(using = TenthSecond.TenthSecondDeserializer.class)
	private TenthSecond tenthSecond;

	public Year getYear() {
		return year;
	}

	public void setYear(Year year) {
		this.year = year;
	}

	public Month getMonth() {
		return month;
	}

	public void setMonth(Month month) {
		this.month = month;
	}

	public Day getDay() {
		return day;
	}

	public void setDay(Day day) {
		this.day = day;
	}

	public SummerTime getSummerTime() {
		return summerTime;
	}

	public void setSummerTime(SummerTime summerTime) {
		this.summerTime = summerTime;
	}

	public Holiday getHoliday() {
		return holiday;
	}

	public void setHoliday(Holiday holiday) {
		this.holiday = holiday;
	}

	public DayOfWeek getDayofWeek() {
		return dayofWeek;
	}

	public void setDayofWeek(DayOfWeek dayofWeek) {
		this.dayofWeek = dayofWeek;
	}

	public Hour getHour() {
		return hour;
	}

	public void setHour(Hour hour) {
		this.hour = hour;
	}

	public Minute getMinute() {
		return minute;
	}

	public void setMinute(Minute minute) {
		this.minute = minute;
	}

	public Second getSecond() {
		return second;
	}

	public void setSecond(Second second) {
		this.second = second;
	}

	public TenthSecond getTenthSecond() {
		return tenthSecond;
	}

	public void setTenthSecond(TenthSecond tenthSecond) {
		this.tenthSecond = tenthSecond;
	}

	TimeMark() {
		super(false);
	}
}