package j2735.AddGrpB;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import asn2pojo.runtime.annotations.Asn1Property;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 *******************************************************************************
 *
 * This source file was generated by a tool. Beware manual edits might be
 * overwritten in future releases. asn1jvm v1.0-SNAPSHOT
 *
 *******************************************************************************
 * Copyright 2024 USDOT
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class TimeMark extends Asn1Sequence {

	@Asn1Property(tag = 0)
	@JsonDeserialize(using = Year.YearDeserializer.class)
	private Year year;
	@Asn1Property(tag = 1)
	@JsonDeserialize(using = Month.MonthDeserializer.class)
	private Month month;
	@Asn1Property(tag = 2)
	@JsonDeserialize(using = Day.DayDeserializer.class)
	private Day day;
	@Asn1Property(tag = 3)
	private SummerTime summerTime;
	@Asn1Property(tag = 4)
	private Holiday holiday;
	@Asn1Property(tag = 5)
	private DayOfWeek dayofWeek;
	@Asn1Property(tag = 6)
	@JsonDeserialize(using = Hour.HourDeserializer.class)
	private Hour hour;
	@Asn1Property(tag = 7)
	@JsonDeserialize(using = Minute.MinuteDeserializer.class)
	private Minute minute;
	@Asn1Property(tag = 8)
	@JsonDeserialize(using = Second.SecondDeserializer.class)
	private Second second;
	@Asn1Property(tag = 9)
	@JsonDeserialize(using = TenthSecond.TenthSecondDeserializer.class)
	private TenthSecond tenthSecond;

	TimeMark() {
		super(false);
	}
}