package j2735.AddGrpB;

import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import asn2pojo.runtime.serialization.IntegerDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class Year extends Asn1Integer {

	public Year() {
		super(1L, 65535L);
	}

	@JsonCreator
	public Year(long value) {
		this();
		this.value = value;
	}

	public static class YearDeserializer extends IntegerDeserializer<Year> {
		public YearDeserializer() {
			super(Year.class);
		}

		@Override
		protected Year construct() {
			return new Year();
		}
	}
}