#!/bin/bash
mkdir common
cp Angle.java common
cp ComputedLane.java common
cp DYear.java common
cp DeltaAngle.java common
cp DescriptiveName.java common
cp DrivenLineOffsetLg.java common
cp DrivenLineOffsetSm.java common
cp Elevation.java common
cp Extent.java common
cp ExtentDeserializer.java common
cp ExtentSerializer.java common
cp FurtherInfoID.java common
cp HeadingSlice.java common
cp HeadingSliceDeserializer.java common
cp LaneDataAttribute.java common
cp LaneDataAttributeList.java common
cp LaneID.java common
cp LaneWidth.java common
cp Latitude.java common
cp Longitude.java common
cp MergeDivergeNodeAngle.java common
cp MinuteOfTheYear.java common
cp MsgCount.java common
cp NodeAttributeSetXY.java common
cp NodeAttributeXY.java common
cp NodeAttributeXYDeserializer.java common
cp NodeAttributeXYList.java common
cp NodeAttributeXYSerializer.java common
cp NodeListXY.java common
cp NodeOffsetPointXY.java common
cp NodeSetXY.java common
cp NodeXY.java common
cp Node_LLmD_64b.java common
cp Node_XY_20b.java common
cp Node_XY_22b.java common
cp Node_XY_24b.java common
cp Node_XY_26b.java common
cp Node_XY_28b.java common
cp Node_XY_32b.java common
cp OffsetLL_B12.java common
cp OffsetLL_B14.java common
cp OffsetLL_B16.java common
cp OffsetLL_B18.java common
cp OffsetLL_B22.java common
cp OffsetLL_B24.java common
cp Offset_B10.java common
cp Offset_B11.java common
cp Offset_B12.java common
cp Offset_B13.java common
cp Offset_B14.java common
cp Offset_B16.java common
cp Position3D.java common
cp RegionId.java common
cp RegionalExtension.java common
cp RegulatorySpeedLimit.java common
cp RoadRegulatorID.java common
cp RoadSegmentID.java common
cp RoadSegmentReferenceID.java common
cp RoadwayCrownAngle.java common
cp SSPindex.java common
cp Scale_B12.java common
cp SegmentAttributeXY.java common
cp SegmentAttributeXYDeserializer.java common
cp SegmentAttributeXYList.java common
cp SegmentAttributeXYSerializer.java common
cp SpeedLimitList.java common
cp SpeedLimitType.java common
cp SpeedLimitTypeDeserializer.java common
cp SpeedLimitTypeSerializer.java common
cp Velocity.java common
