package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import com.fasterxml.jackson.annotation.JsonProperty;
import us.dot.its.jpo.ode.plugin.j2735.REGION.Reg_MovementState;
import us.dot.its.jpo.ode.plugin.types.Asn1SequenceOf;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

/**
 * 
 *******************************************************************************
 *
 * This source file was generated by a tool. Beware manual edits might be
 * overwritten in future releases. asn1jvm v1.0-SNAPSHOT
 *
 *******************************************************************************
 * Copyright 2024 USDOT
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class MovementState extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	private DescriptiveName movementName;
	@Asn1Property(tag = 1)
	@JsonDeserialize(using = SignalGroupID.SignalGroupIDDeserializer.class)
	private SignalGroupID signalGroup;
	@Asn1Property(tag = 2, name = "state-time-speed")
	@JsonProperty("state-time-speed")
	@JacksonXmlElementWrapper(localName = "state-time-speed")
	@JacksonXmlProperty(localName = "MovementEvent")
	private MovementEventList state_time_speed;
	@Asn1Property(tag = 3, optional = true)
	@JacksonXmlElementWrapper(localName = "maneuverAssistList")
	@JacksonXmlProperty(localName = "ConnectionManeuverAssist")
	private ManeuverAssistList maneuverAssistList;
	@Asn1Property(tag = 4, optional = true)
	private SequenceOfRegional regional;

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_MovementState> {
		SequenceOfRegional() {
			super(Reg_MovementState.class, 1L, 4L);
		}
	}

	MovementState() {
		super(true);
	}
}