package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 *******************************************************************************
 *
 * This source file was generated by a tool. Beware manual edits might be
 * overwritten in future releases. asn1jvm v1.0-SNAPSHOT
 *
 *******************************************************************************
 * Copyright 2024 USDOT
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class PathHistoryPoint extends Asn1Sequence {

	@Asn1Property(tag = 0)
	@JsonDeserialize(using = OffsetLL_B18.OffsetLL_B18Deserializer.class)
	private OffsetLL_B18 latOffset;
	@Asn1Property(tag = 1)
	@JsonDeserialize(using = OffsetLL_B18.OffsetLL_B18Deserializer.class)
	private OffsetLL_B18 lonOffset;
	@Asn1Property(tag = 2)
	@JsonDeserialize(using = VertOffset_B12.VertOffset_B12Deserializer.class)
	private VertOffset_B12 elevationOffset;
	@Asn1Property(tag = 3)
	@JsonDeserialize(using = TimeOffset.TimeOffsetDeserializer.class)
	private TimeOffset timeOffset;
	@Asn1Property(tag = 4, optional = true)
	@JsonDeserialize(using = Speed.SpeedDeserializer.class)
	private Speed speed;
	@Asn1Property(tag = 5, optional = true)
	private PositionalAccuracy posAccuracy;
	@Asn1Property(tag = 6, optional = true)
	@JsonDeserialize(using = CoarseHeading.CoarseHeadingDeserializer.class)
	private CoarseHeading heading;

	PathHistoryPoint() {
		super(true);
	}
}