package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import us.dot.its.jpo.ode.plugin.j2735.REGION.Reg_PersonalSafetyMessage;
import us.dot.its.jpo.ode.plugin.types.Asn1SequenceOf;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 *******************************************************************************
 *
 * This source file was generated by a tool. Beware manual edits might be
 * overwritten in future releases. asn1jvm v1.0-SNAPSHOT
 *
 *******************************************************************************
 * Copyright 2024 USDOT
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class PersonalSafetyMessage extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private PersonalDeviceUserType basicType;
	@Asn1Property(tag = 1)
	@JsonDeserialize(using = DSecond.DSecondDeserializer.class)
	private DSecond secMark;
	@Asn1Property(tag = 2)
	@JsonDeserialize(using = MsgCount.MsgCountDeserializer.class)
	private MsgCount msgCnt;
	@Asn1Property(tag = 3)
	private TemporaryID id;
	@Asn1Property(tag = 4)
	private Position3D position;
	@Asn1Property(tag = 5)
	private PositionalAccuracy accuracy;
	@Asn1Property(tag = 6)
	@JsonDeserialize(using = Velocity.VelocityDeserializer.class)
	private Velocity speed;
	@Asn1Property(tag = 7)
	@JsonDeserialize(using = Heading.HeadingDeserializer.class)
	private Heading heading;
	@Asn1Property(tag = 8, optional = true)
	private AccelerationSet4Way accelSet;
	@Asn1Property(tag = 9, optional = true)
	private PathHistory pathHistory;
	@Asn1Property(tag = 10, optional = true)
	private PathPrediction pathPrediction;
	@Asn1Property(tag = 11, optional = true)
	private PropelledInformation propulsion;
	@Asn1Property(tag = 12, optional = true)
	private PersonalDeviceUsageState useState;
	@Asn1Property(tag = 13, optional = true)
	private PersonalCrossingRequest crossRequest;
	@Asn1Property(tag = 14, optional = true)
	private PersonalCrossingInProgress crossState;
	@Asn1Property(tag = 15, optional = true)
	private NumberOfParticipantsInCluster clusterSize;
	@Asn1Property(tag = 16, optional = true)
	@JsonDeserialize(using = PersonalClusterRadius.PersonalClusterRadiusDeserializer.class)
	private PersonalClusterRadius clusterRadius;
	@Asn1Property(tag = 17, optional = true)
	private PublicSafetyEventResponderWorkerType eventResponderType;
	@Asn1Property(tag = 18, optional = true)
	private PublicSafetyAndRoadWorkerActivity activityType;
	@Asn1Property(tag = 19, optional = true)
	private PublicSafetyDirectingTrafficSubType activitySubType;
	@Asn1Property(tag = 20, optional = true)
	private PersonalAssistive assistType;
	@Asn1Property(tag = 21, optional = true)
	private UserSizeAndBehaviour sizing;
	@Asn1Property(tag = 22, optional = true)
	private Attachment attachment;
	@Asn1Property(tag = 23, optional = true)
	@JsonDeserialize(using = AttachmentRadius.AttachmentRadiusDeserializer.class)
	private AttachmentRadius attachmentRadius;
	@Asn1Property(tag = 24, optional = true)
	private AnimalType animalType;
	@Asn1Property(tag = 25, optional = true)
	private SequenceOfRegional regional;

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_PersonalSafetyMessage> {
		SequenceOfRegional() {
			super(Reg_PersonalSafetyMessage.class, 1L, 4L);
		}
	}

	PersonalSafetyMessage() {
		super(true);
	}
}