/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import com.fasterxml.jackson.annotation.JsonProperty;
import us.dot.its.jpo.ode.plugin.j2735.region.Reg_SupplementalVehicleExtensions;
import us.dot.its.jpo.ode.plugin.types.Asn1SequenceOf;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class SupplementalVehicleExtensions extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "classification", optional = true)
	@JsonProperty("classification")
	private BasicVehicleClass classification;
	@Asn1Property(tag = 1, name = "classDetails", optional = true)
	@JsonProperty("classDetails")
	private VehicleClassification classDetails;
	@Asn1Property(tag = 2, name = "vehicleData", optional = true)
	@JsonProperty("vehicleData")
	private VehicleData vehicleData;
	@Asn1Property(tag = 3, name = "weatherReport", optional = true)
	@JsonProperty("weatherReport")
	private WeatherReport weatherReport;
	@Asn1Property(tag = 4, name = "weatherProbe", optional = true)
	@JsonProperty("weatherProbe")
	private WeatherProbe weatherProbe;
	@Asn1Property(tag = 5, name = "obstacle", optional = true)
	@JsonProperty("obstacle")
	private ObstacleDetection obstacle;
	@Asn1Property(tag = 6, name = "status", optional = true)
	@JsonProperty("status")
	private DisabledVehicle status;
	@Asn1Property(tag = 7, name = "speedProfile", optional = true)
	@JsonProperty("speedProfile")
	private SpeedProfile speedProfile;
	@Asn1Property(tag = 8, name = "theRTCM", optional = true)
	@JsonProperty("theRTCM")
	private RTCMPackage theRTCM;
	@Asn1Property(tag = 9, name = "regional", optional = true)
	@JsonProperty("regional")
	private SequenceOfRegional regional;

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_SupplementalVehicleExtensions> {
		SequenceOfRegional() {
			super(Reg_SupplementalVehicleExtensions.class, 1L, 4L);
		}
	}

	SupplementalVehicleExtensions() {
		super(true);
	}
}