package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 *******************************************************************************
 *
 * This source file was generated by a tool. Beware manual edits might be
 * overwritten in future releases. asn1jvm v1.0-SNAPSHOT
 *
 *******************************************************************************
 * Copyright 2024 USDOT
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class VehicleStatus extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	private ExteriorLights lights;
	@Asn1Property(tag = 1, optional = true)
	private LightbarInUse lightBar;
	@Asn1Property(tag = 2, optional = true)
	private WiperSet wipers;
	@Asn1Property(tag = 3, optional = true)
	private BrakeSystemStatus brakeStatus;
	@Asn1Property(tag = 4, optional = true)
	private BrakeAppliedPressure brakePressure;
	@Asn1Property(tag = 5, optional = true)
	@JsonDeserialize(using = CoefficientOfFriction.CoefficientOfFrictionDeserializer.class)
	private CoefficientOfFriction roadFriction;
	@Asn1Property(tag = 6, optional = true)
	@JsonDeserialize(using = SunSensor.SunSensorDeserializer.class)
	private SunSensor sunData;
	@Asn1Property(tag = 7, optional = true)
	private RainSensor rainData;
	@Asn1Property(tag = 8, optional = true)
	@JsonDeserialize(using = AmbientAirTemperature.AmbientAirTemperatureDeserializer.class)
	private AmbientAirTemperature airTemp;
	@Asn1Property(tag = 9, optional = true)
	@JsonDeserialize(using = AmbientAirPressure.AmbientAirPressureDeserializer.class)
	private AmbientAirPressure airPres;
	@Asn1Property(tag = 10, optional = true)
	private Asn1Sequence steering;
	@Asn1Property(tag = 11, optional = true)
	private Asn1Sequence accelSets;
	@Asn1Property(tag = 12, optional = true)
	private Asn1Sequence object;
	@Asn1Property(tag = 13, optional = true)
	private FullPositionVector fullPos;
	@Asn1Property(tag = 14, optional = true)
	@JsonDeserialize(using = ThrottlePosition.ThrottlePositionDeserializer.class)
	private ThrottlePosition throttlePos;
	@Asn1Property(tag = 15, optional = true)
	private SpeedandHeadingandThrottleConfidence speedHeadC;
	@Asn1Property(tag = 16, optional = true)
	private SpeedConfidence speedC;
	@Asn1Property(tag = 17, optional = true)
	private Asn1Sequence vehicleData;
	@Asn1Property(tag = 18, optional = true)
	private VehicleIdent vehicleIdent;
	@Asn1Property(tag = 19, optional = true)
	private J1939data j1939data;
	@Asn1Property(tag = 20, optional = true)
	private Asn1Sequence weatherReport;
	@Asn1Property(tag = 21, optional = true)
	private GNSSstatus gnssStatus;

	VehicleStatus() {
		super(true);
	}
}