package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1Choice;
import lombok.Getter;
import lombok.Setter;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import us.dot.its.jpo.ode.plugin.j2735.REGION.Reg_VerticalOffset;
import java.util.Optional;
import java.util.List;
import us.dot.its.jpo.ode.plugin.types.Asn1Type;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 *******************************************************************************
 *
 * This source file was generated by a tool. Beware manual edits might be
 * overwritten in future releases. asn1jvm v1.0-SNAPSHOT
 *
 *******************************************************************************
 * Copyright 2024 USDOT
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************
 * 
 */
@Getter
@Setter
@JsonInclude(Include.NON_NULL)
public class VerticalOffset extends Asn1Choice {

	@Asn1Property(tag = 0)
	@JsonDeserialize(using = VertOffset_B07.VertOffset_B07Deserializer.class)
	private VertOffset_B07 offset1;
	@Asn1Property(tag = 1)
	@JsonDeserialize(using = VertOffset_B08.VertOffset_B08Deserializer.class)
	private VertOffset_B08 offset2;
	@Asn1Property(tag = 2)
	@JsonDeserialize(using = VertOffset_B09.VertOffset_B09Deserializer.class)
	private VertOffset_B09 offset3;
	@Asn1Property(tag = 3)
	@JsonDeserialize(using = VertOffset_B10.VertOffset_B10Deserializer.class)
	private VertOffset_B10 offset4;
	@Asn1Property(tag = 4)
	@JsonDeserialize(using = VertOffset_B11.VertOffset_B11Deserializer.class)
	private VertOffset_B11 offset5;
	@Asn1Property(tag = 5)
	@JsonDeserialize(using = VertOffset_B12.VertOffset_B12Deserializer.class)
	private VertOffset_B12 offset6;
	@Asn1Property(tag = 6)
	@JsonDeserialize(using = Elevation.ElevationDeserializer.class)
	private Elevation elevation;
	@Asn1Property(tag = 7)
	private Reg_VerticalOffset regional;

	VerticalOffset() {
		super(false);
	}

	@Override
	protected List<Optional<Asn1Type>> listTypes() {
		return null;
	}
}