package j2735.AddGrpC;

import asn2pojo.runtime.serialization.OpenTypeDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class ConnectionManeuverAssist_addGrpCReg_ConnectionManeuverAssistValueDeserializer
		extends
			OpenTypeDeserializer<ConnectionManeuverAssist_addGrpC> {

	public ConnectionManeuverAssist_addGrpCReg_ConnectionManeuverAssistValueDeserializer() {
		super(ConnectionManeuverAssist_addGrpC.class, "ConnectionManeuverAssist_addGrpC");
	}
}