package j2735.AddGrpC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import asn2pojo.runtime.annotations.Asn1Property;
import j2735.DSRC.NodeOffsetPointXY;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class ConnectionManeuverAssist_addGrpC extends Asn1Sequence {

	@Asn1Property(tag = 0)
	@JacksonXmlElementWrapper(localName = "vehicleToLanePositions")
	@JacksonXmlProperty(localName = "VehicleToLanePosition")
	private VehicleToLanePositionList vehicleToLanePositions;
	@Asn1Property(tag = 1, optional = true)
	private NodeOffsetPointXY rsuDistanceFromAnchor;

	public VehicleToLanePositionList getVehicleToLanePositions() {
		return vehicleToLanePositions;
	}

	public void setVehicleToLanePositions(VehicleToLanePositionList vehicleToLanePositions) {
		this.vehicleToLanePositions = vehicleToLanePositions;
	}

	public NodeOffsetPointXY getRsuDistanceFromAnchor() {
		return rsuDistanceFromAnchor;
	}

	public void setRsuDistanceFromAnchor(NodeOffsetPointXY rsuDistanceFromAnchor) {
		this.rsuDistanceFromAnchor = rsuDistanceFromAnchor;
	}

	ConnectionManeuverAssist_addGrpC() {
		super(false);
	}
}