package j2735.AddGrpC;

import com.fasterxml.jackson.annotation.JsonRootName;
import j2735.REGION.Reg_ConnectionManeuverAssist;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonRootName("Reg_ConnectionManeuverAssist")
public class ConnectionManeuverAssist_addGrpCReg_ConnectionManeuverAssist
		extends
			Reg_ConnectionManeuverAssist<ConnectionManeuverAssist_addGrpC> {

	public ConnectionManeuverAssist_addGrpCReg_ConnectionManeuverAssist() {
		super(3, "ConnectionManeuverAssist_addGrpC");
	}

	@Override
	@JsonSerialize(using = ConnectionManeuverAssist_addGrpCReg_ConnectionManeuverAssistValueSerializer.class)
	public ConnectionManeuverAssist_addGrpC getRegExtValue() {
		return super.getRegExtValue();
	}

	@Override
	@JsonDeserialize(using = ConnectionManeuverAssist_addGrpCReg_ConnectionManeuverAssistValueDeserializer.class)
	public void setRegExtValue(ConnectionManeuverAssist_addGrpC value) {
		super.setRegExtValue(value);
	}
}