package j2735.AddGrpC;

import asn2pojo.runtime.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonSerialize(using = EmissionTypeSerializer.class)
@JsonDeserialize(using = EmissionTypeDeserializer.class)
public enum EmissionType implements Asn1Enumerated {
	typeA(0, "typeA"), typeB(1, "typeB"), typeC(2, "typeC"), typeD(3, "typeD"), typeE(4, "typeE");

	private final int index;
	private final String name;

	public int getIndex() {
		return index;
	}

	public String getName() {
		return name;
	}

	public boolean hasExtensionMarker() {
		return false;
	}

	private EmissionType(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public int maxIndex() {
		return 4;
	}
}