package j2735.AddGrpC;

import asn2pojo.runtime.serialization.OpenTypeSerializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class IntersectionState_addGrpCReg_IntersectionStateValueSerializer
		extends
			OpenTypeSerializer<IntersectionState_addGrpC> {

	public IntersectionState_addGrpCReg_IntersectionStateValueSerializer() {
		super(IntersectionState_addGrpC.class, "regExtValue", "IntersectionState_addGrpC");
	}
}