package j2735.AddGrpC;

import com.fasterxml.jackson.annotation.JsonRootName;
import j2735.REGION.Reg_IntersectionState;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonRootName("Reg_IntersectionState")
public class IntersectionState_addGrpCReg_IntersectionState extends Reg_IntersectionState<IntersectionState_addGrpC> {

	public IntersectionState_addGrpCReg_IntersectionState() {
		super(3, "IntersectionState_addGrpC");
	}

	@Override
	@JsonSerialize(using = IntersectionState_addGrpCReg_IntersectionStateValueSerializer.class)
	public IntersectionState_addGrpC getRegExtValue() {
		return super.getRegExtValue();
	}

	@Override
	@JsonDeserialize(using = IntersectionState_addGrpCReg_IntersectionStateValueDeserializer.class)
	public void setRegExtValue(IntersectionState_addGrpC value) {
		super.setRegExtValue(value);
	}
}