package j2735.AddGrpC;

import asn2pojo.runtime.serialization.OpenTypeSerializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class Position3D_addGrpCReg_Position3DValueSerializer extends OpenTypeSerializer<Position3D_addGrpC> {

	public Position3D_addGrpCReg_Position3DValueSerializer() {
		super(Position3D_addGrpC.class, "regExtValue", "Position3D_addGrpC");
	}
}