package j2735.AddGrpC;

import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import j2735.DSRC.StationID;
import asn2pojo.runtime.annotations.Asn1Property;
import j2735.DSRC.PrioritizationResponseStatus;
import j2735.DSRC.SignalGroupID;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class PrioritizationResponse extends Asn1Sequence {

	@Asn1Property(tag = 0)
	@JsonDeserialize(using = StationID.StationIDDeserializer.class)
	private StationID stationID;
	@Asn1Property(tag = 1)
	private PrioritizationResponseStatus priorState;
	@Asn1Property(tag = 2)
	@JsonDeserialize(using = SignalGroupID.SignalGroupIDDeserializer.class)
	private SignalGroupID signalGroup;

	public StationID getStationID() {
		return stationID;
	}

	public void setStationID(StationID stationID) {
		this.stationID = stationID;
	}

	public PrioritizationResponseStatus getPriorState() {
		return priorState;
	}

	public void setPriorState(PrioritizationResponseStatus priorState) {
		this.priorState = priorState;
	}

	public SignalGroupID getSignalGroup() {
		return signalGroup;
	}

	public void setSignalGroup(SignalGroupID signalGroup) {
		this.signalGroup = signalGroup;
	}

	PrioritizationResponse() {
		super(true);
	}
}