package j2735.AddGrpC;

import asn2pojo.runtime.serialization.OpenTypeSerializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class RestrictionUserType_addGrpCReg_RestrictionUserTypeValueSerializer
		extends
			OpenTypeSerializer<RestrictionUserType_addGrpC> {

	public RestrictionUserType_addGrpCReg_RestrictionUserTypeValueSerializer() {
		super(RestrictionUserType_addGrpC.class, "regExtValue", "RestrictionUserType_addGrpC");
	}
}