package j2735.AddGrpC;

import asn2pojo.runtime.annotations.Asn1Property;
import asn2pojo.runtime.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import j2735.DSRC.LaneID;
import j2735.DSRC.StationID;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class VehicleToLanePosition extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private StationID stationID;
	@Asn1Property(tag = 1)
	private LaneID laneID;

	public StationID getStationID() {
		return stationID;
	}

	public void setStationID(StationID stationID) {
		this.stationID = stationID;
	}

	public LaneID getLaneID() {
		return laneID;
	}

	public void setLaneID(LaneID laneID) {
		this.laneID = laneID;
	}

	VehicleToLanePosition() {
		super(true);
	}
}