package j2735.NTCIP;

import asn2pojo.runtime.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import asn2pojo.runtime.serialization.IntegerDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class EssMobileFriction extends Asn1Integer {

	public EssMobileFriction() {
		super(0L, 101L);
	}

	@JsonCreator
	public EssMobileFriction(long value) {
		this();
		this.value = value;
	}

	public static class EssMobileFrictionDeserializer extends IntegerDeserializer<EssMobileFriction> {
		public EssMobileFrictionDeserializer() {
			super(EssMobileFriction.class);
		}

		@Override
		protected EssMobileFriction construct() {
			return new EssMobileFriction();
		}
	}
}