package j2735.NTCIP;

import asn2pojo.runtime.serialization.EnumeratedDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class EssPrecipYesNoDeserializer extends EnumeratedDeserializer<EssPrecipYesNo> {

	EssPrecipYesNoDeserializer() {
		super(EssPrecipYesNo.class);
	}

	@Override
	protected EssPrecipYesNo[] listEnumValues() {
		return EssPrecipYesNo.values();
	}
}