package j2735.NTCIP;

import asn2pojo.runtime.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonSerialize(using = EssPrecipSituationSerializer.class)
@JsonDeserialize(using = EssPrecipSituationDeserializer.class)
public enum EssPrecipSituation implements Asn1Enumerated {
	other(1, "other"), unknown(2, "unknown"), noPrecipitation(3, "noPrecipitation"), unidentifiedSlight(4,
			"unidentifiedSlight"), unidentifiedModerate(5, "unidentifiedModerate"), unidentifiedHeavy(6,
					"unidentifiedHeavy"), snowSlight(7, "snowSlight"), snowModerate(8, "snowModerate"), snowHeavy(9,
							"snowHeavy"), rainSlight(10, "rainSlight"), rainModerate(11, "rainModerate"), rainHeavy(12,
									"rainHeavy"), frozenPrecipitationSlight(13,
											"frozenPrecipitationSlight"), frozenPrecipitationModerate(14,
													"frozenPrecipitationModerate"), frozenPrecipitationHeavy(15,
															"frozenPrecipitationHeavy");

	private final int index;
	private final String name;

	public int getIndex() {
		return index;
	}

	public String getName() {
		return name;
	}

	public boolean hasExtensionMarker() {
		return false;
	}

	private EssPrecipSituation(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public int maxIndex() {
		return -1;
	}
}